/* Open cloze (B2 First Part 2) practice set 4: lexico-grammar. Multi-word verbs, fixed phrases, collocations, verb patterns and reporting. Original sentences. Drafted, not a verified frequency list: teacher review advised. UK spelling. Answers are one word, no contractions. Load AFTER cloze.js: this file adds to window.CLOZE. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"c01",c:"pv",s:"Over two hundred runners took ___ in the charity race.",a:"part",o:["place","care","turn"],w:"Take part in means participate."},
{id:"c02",c:"pv",s:"We set ___ at dawn to avoid the traffic.",a:"off",alt:["out"],o:["up","down","over"],w:"Set off or set out means begin a journey."},
{id:"c03",c:"pv",s:"Scientists carried ___ a series of experiments on the new drug.",a:"out",o:["off","up","away"],w:"Carry out means do and complete a task."},
{id:"c04",c:"pv",s:"The weather turned ___ to be much better than the forecast.",a:"out",o:["up","off","over"],w:"Turn out to be describes a surprising result."},
{id:"c05",c:"pv",s:"She decided to give ___ smoking last year.",a:"up",o:["out","off","away"],w:"Give up means stop doing something."},
{id:"c06",c:"pv",s:"I came ___ my old diary while I was tidying the attic.",a:"across",alt:["upon"],o:["along","over","through"],w:"Come across means find by chance."},
{id:"c07",c:"pv",s:"Can you find ___ what time the train leaves?",a:"out",o:["up","off","over"],w:"Find out means discover information."},
{id:"c08",c:"pv",s:"If you keep spending money like that, you will end ___ broke.",a:"up",o:["out","off","in"],w:"End up + adjective means finally be in a situation."},
{id:"c09",c:"pv",s:"The manager promised to deal ___ the complaint immediately.",a:"with",o:["on","by","at"],w:"Deal with means take action about."},
{id:"c10",c:"pv",s:"I get ___ very well with my new colleagues.",a:"on",alt:["along"],o:["up","off","by"],w:"Get on or get along means have a good relationship."},
{id:"c11",c:"pv",s:"Nothing can make ___ for the time we have lost.",a:"up",o:["out","off","over"],w:"Make up for means compensate for."},
{id:"c12",c:"pv",s:"I cannot put up ___ this noise any longer.",a:"with",o:["to","for","on"],w:"Put up with means tolerate."},
{id:"c13",c:"fixed",s:"On the other ___, the journey was cheaper than expected.",a:"hand",o:["side","way","part"],w:"On the one hand ... on the other hand."},
{id:"c14",c:"fixed",s:"In the ___, we decided to stay at home.",a:"end",o:["finish","last","close"],w:"In the end means finally."},
{id:"c15",c:"fixed",s:"At ___, we did not understand the rules, but later it became clear.",a:"first",o:["start","begin","least"],w:"At first contrasts with later."},
{id:"c16",c:"fixed",s:"As a ___, many shops had to close.",a:"result",alt:["consequence"],o:["reason","cause","effect"],w:"As a result introduces a consequence."},
{id:"c17",c:"fixed",s:"It was a difficult choice, but ___ the whole I think we chose well.",a:"on",o:["in","at","by"],w:"On the whole means in general."},
{id:"c18",c:"fixed",s:"By the ___, did you remember to buy the tickets?",a:"way",o:["time","end","side"],w:"By the way adds a new or less important topic."},
{id:"c19",c:"fixed",s:"I cannot come. I have too much work and, ___ any case, I do not feel well.",a:"in",o:["on","at","by"],w:"In any case means whatever happens."},
{id:"c20",c:"fixed",s:"You can stay with us for the time ___.",a:"being",o:["now","here","going"],w:"For the time being means for now, but not permanently."},
{id:"c21",c:"fixed",s:"The doctor will see you soon. In the ___, please take a seat.",a:"meantime",alt:["meanwhile"],o:["moment","while","time"],w:"In the meantime means while waiting."},
{id:"c22",c:"fixed",s:"Some animals, for ___, sleep standing up.",a:"example",alt:["instance"],o:["sample","case","reason"],w:"For example or for instance introduces an illustration."},
{id:"c23",c:"fixed",s:"I broke the vase by ___; I did not mean to.",a:"accident",alt:["mistake","chance"],o:["purpose","luck","design"],w:"By accident is the opposite of on purpose."},
{id:"c24",c:"colloc",s:"The wedding will take ___ in a small church.",a:"place",o:["part","care","turn"],w:"Events take place. People take part."},
{id:"c25",c:"colloc",s:"Please make ___ that you lock the door when you leave.",a:"sure",alt:["certain"],o:["true","right","safe"],w:"Make sure or make certain."},
{id:"c26",c:"colloc",s:"Students must pay ___ to the teacher during lessons.",a:"attention",alt:["heed"],o:["care","interest","concern"],w:"Pay attention to."},
{id:"c27",c:"colloc",s:"It was lovely to meet you. Let us keep in ___.",a:"touch",alt:["contact"],o:["reach","link","line"],w:"Keep in touch means stay in contact."},
{id:"c28",c:"colloc",s:"You should take ___ of the good weather and go for a walk.",a:"advantage",o:["use","benefit","profit"],w:"Take advantage of."},
{id:"c29",c:"colloc",s:"She has made great ___ in her English this year.",a:"progress",o:["process","result","gain"],w:"Make progress. Watch the spelling: progress."},
{id:"c30",c:"colloc",s:"Social media plays a major ___ in how young people communicate.",a:"part",alt:["role"],o:["place","game","piece"],w:"Play a part or play a role."},
{id:"c31",c:"colloc",s:"He caught ___ of a rare bird as he walked through the forest.",a:"sight",o:["view","look","glimpse"],w:"Catch sight of means see suddenly."},
{id:"c32",c:"colloc",s:"It is important to do your ___ to protect the environment.",a:"best",alt:["bit","part"],o:["most","better","good"],w:"Do your best, or do your bit."},
{id:"c33",c:"colloc",s:"The company went out of ___ after thirty years.",a:"business",o:["work","trade","money"],w:"Go out of business means stop trading."},
{id:"c34",c:"verb",s:"He suggested ___ to the beach for the day.",a:"going",o:["go","gone","goes"],w:"Suggest + -ing."},
{id:"c35",c:"verb",s:"She admitted ___ the window.",a:"breaking",o:["break","broke","broken"],w:"Admit + -ing."},
{id:"c36",c:"verb",s:"She is said ___ be the richest woman in Europe.",a:"to",o:["for","that","by"],w:"Passive reporting: is said to + infinitive."},
{id:"c37",c:"verb",s:"My parents want me ___ become a doctor.",a:"to",o:["that","for","of"],w:"Want someone to + infinitive."},
{id:"c38",c:"verb",s:"He told me ___ he would call me the next day.",a:"that",o:["what","if","to"],w:"Reported statement: told someone that + clause."},
{id:"c39",c:"verb",s:"She ___ me that she was moving to Canada.",a:"told",o:["said","spoke","talked"],w:"Tell is followed by a person. Say is not."},
{id:"c40",c:"verb",s:"He spoke quietly so ___ not to wake the baby.",a:"as",o:["that","to","if"],w:"So as (not) to + infinitive shows purpose."},
{id:"c41",c:"verb",s:"I look forward to ___ from you soon.",a:"hearing",o:["hear","heard","hears"],w:"Look forward to + -ing, because to is a preposition here."},
{id:"c42",c:"verb",s:"I prefer tea ___ coffee.",a:"to",o:["than","from","over"],w:"Prefer one thing to another."},
{id:"c43",c:"verb",s:"He insisted ___ paying for the meal.",a:"on",o:["in","at","for"],w:"Insist on + -ing."}
]);
