/* Open cloze (B2 First Part 2) practice set 3: linkers, comparison and degree, prepositions. Original sentences. Drafted, not a verified frequency list: teacher review advised. UK spelling. Answers are one word, no contractions. Load AFTER cloze.js: this file adds to window.CLOZE. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"b01",c:"link",s:"I wonder ___ the shop is open on Sundays.",a:"if",alt:["whether"],o:["that","what","so"],w:"If or whether introduces an indirect yes/no question."},
{id:"b02",c:"link",s:"She looked at me as ___ nothing had happened.",a:"though",alt:["if"],o:["so","long","much"],w:"As though or as if + past perfect for an unreal comparison."},
{id:"b03",c:"link",s:"She speaks French and German, as ___ as English.",a:"well",o:["much","good","long"],w:"As well as means and also."},
{id:"b04",c:"link",s:"Some people love big cities, ___ others prefer village life.",a:"while",alt:["whereas","but"],o:["unless","until","so"],w:"While or whereas shows a contrast between two groups."},
{id:"b05",c:"link",s:"She spoke slowly ___ that everyone could understand.",a:"so",o:["such","too","very"],w:"So that + clause shows purpose."},
{id:"b06",c:"link",s:"Take an umbrella in ___ it rains.",a:"case",o:["order","time","spite"],w:"In case + clause: as a precaution."},
{id:"b07",c:"link",s:"You can borrow my car as ___ as you drive carefully.",a:"long",o:["far","well","many"],w:"As long as means on condition that."},
{id:"b08",c:"link",s:"Hurry up, ___ you will miss the bus.",a:"otherwise",alt:["or"],o:["although","unless","however"],w:"Otherwise means if you do not."},
{id:"b09",c:"link",s:"I did not go to the party. ___, I stayed at home and read a book.",a:"instead",o:["although","unless","because"],w:"Instead means in place of the thing just mentioned."},
{id:"b10",c:"link",s:"I will not change my mind, even ___ you ask me again.",a:"if",o:["unless","because","so"],w:"Even if + a possible future situation."},
{id:"b11",c:"link",s:"I cannot decide ___ to accept the job or not.",a:"whether",o:["if","that","what"],w:"Whether + to-infinitive. If cannot be used here."},
{id:"b12",c:"link",s:"___ hard I try, I cannot open this jar.",a:"however",o:["although","whatever","whenever"],w:"However + adjective or adverb means no matter how."},
{id:"b13",c:"link",s:"It was not ___ I got home that I realised I had lost my wallet.",a:"until",alt:["till"],o:["since","while","during"],w:"Not until marks the point when something first happened."},
{id:"b14",c:"comp",s:"He was ___ tired that he fell asleep at his desk.",a:"so",o:["such","too","very"],w:"So + adjective + that + result."},
{id:"b15",c:"comp",s:"It was ___ a beautiful day that we decided to have a picnic.",a:"such",o:["so","very","too"],w:"Such + a + adjective + noun + that + result."},
{id:"b16",c:"comp",s:"I was ___ surprised to say anything.",a:"too",o:["so","very","enough"],w:"Too + adjective + to-infinitive means more than is needed to do it."},
{id:"b17",c:"comp",s:"The film was far better ___ I expected.",a:"than",o:["as","that","then"],w:"Comparative + than. Watch the spelling: than, not then."},
{id:"b18",c:"comp",s:"She is not as tall ___ her sister.",a:"as",o:["than","like","that"],w:"Not as + adjective + as."},
{id:"b19",c:"comp",s:"The harder you work, ___ better your results will be.",a:"the",o:["a","more","that"],w:"The + comparative, the + comparative."},
{id:"b20",c:"comp",s:"The longer the journey, the ___ tired we became.",a:"more",o:["most","much","very"],w:"The + comparative, the + comparative. Tired takes more."},
{id:"b21",c:"comp",s:"This is by far the ___ difficult exam I have ever taken.",a:"most",o:["more","very","much"],w:"Superlative of a long adjective: the most + adjective."},
{id:"b22",c:"comp",s:"The new model is ___ more expensive than the old one.",a:"much",alt:["far","even","still"],o:["very","too","so"],w:"Much, far, even or still can strengthen a comparative. Very cannot."},
{id:"b23",c:"comp",s:"No sooner had we sat down ___ the waiter brought the menu.",a:"than",o:["when","that","then"],w:"No sooner ... than. Hardly ... when is the matching pair."},
{id:"b24",c:"comp",s:"I try to eat ___ sugar than I used to.",a:"less",o:["fewer","little","lesser"],w:"Less with uncountable nouns. Fewer is for countable nouns."},
{id:"b25",c:"comp",s:"There were so ___ people at the concert that we could not move.",a:"many",o:["much","lot","few"],w:"So many + countable noun + that + result."},
{id:"b26",c:"prep",s:"Many people are afraid ___ flying.",a:"of",o:["from","at","for"],w:"Afraid of."},
{id:"b27",c:"prep",s:"We enjoyed the trip in spite ___ the rain.",a:"of",o:["from","for","to"],w:"In spite of + noun phrase."},
{id:"b28",c:"prep",s:"The match was cancelled because ___ the weather.",a:"of",o:["from","for","to"],w:"Because of + noun phrase. Because alone needs a clause."},
{id:"b29",c:"prep",s:"Why not walk instead ___ taking the bus?",a:"of",o:["from","to","for"],w:"Instead of + noun or -ing."},
{id:"b30",c:"prep",s:"She has been famous ___ her cooking since she won a TV competition.",a:"for",o:["of","with","about"],w:"Famous for."},
{id:"b31",c:"prep",s:"I have not seen her ___ three weeks.",a:"for",alt:["in"],o:["since","from","during"],w:"For + a length of time."},
{id:"b32",c:"prep",s:"This design is similar ___ the one we used last year.",a:"to",o:["with","as","from"],w:"Similar to."},
{id:"b33",c:"prep",s:"In addition ___ English, she speaks Italian and Greek.",a:"to",o:["of","with","for"],w:"In addition to + noun or -ing."},
{id:"b34",c:"prep",s:"We were introduced ___ each other at the party.",a:"to",o:["with","for","at"],w:"Introduce someone to someone."},
{id:"b35",c:"prep",s:"I am not familiar ___ this software.",a:"with",o:["of","to","for"],w:"Familiar with."},
{id:"b36",c:"prep",s:"The book was written ___ a famous Spanish author.",a:"by",o:["from","of","with"],w:"By + the agent in a passive sentence."},
{id:"b37",c:"prep",s:"Heavy rain prevented us ___ leaving the house.",a:"from",o:["of","to","for"],w:"Prevent someone from + -ing."},
{id:"b38",c:"prep",s:"___ to the forecast, it will snow tomorrow.",a:"according",o:["owing","due","thanks"],w:"According to + a source of information."},
{id:"b39",c:"prep",s:"___ from Maria, everybody passed the test.",a:"apart",alt:["aside"],o:["away","far","other"],w:"Apart from means except for."},
{id:"b40",c:"prep",s:"I am worried ___ my exam results.",a:"about",o:["of","for","with"],w:"Worried about."},
{id:"b41",c:"prep",s:"She specialises ___ marine biology.",a:"in",o:["on","at","for"],w:"Specialise in."}
]);
