/* Open cloze (B2 First Part 2) practice set 2: core function words. Auxiliaries and modals, pronouns, relative words, articles and determiners. Original sentences. Drafted, not a verified frequency list: teacher review advised. UK spelling. Answers are one word, no contractions. Load AFTER cloze.js: this file adds to window.CLOZE. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"a01",c:"aux",s:"By the time we arrived, the film ___ already started.",a:"had",o:["has","was","have"],w:"Past perfect: an action finished before another past action."},
{id:"a02",c:"aux",s:"The new bridge has ___ built to reduce traffic in the town centre.",a:"been",o:["be","being","was"],w:"Present perfect passive: has been + past participle."},
{id:"a03",c:"aux",s:"The results will ___ announced on Friday.",a:"be",o:["been","being","is"],w:"Future passive: will be + past participle."},
{id:"a04",c:"aux",s:"She hates ___ laughed at.",a:"being",o:["be","been","to"],w:"Passive gerund: being + past participle, after verbs like hate, like and avoid."},
{id:"a05",c:"aux",s:"I ___ not realise how late it was until I looked at the clock.",a:"did",o:["was","had","has"],w:"Past simple negative: did + not + base verb."},
{id:"a06",c:"aux",s:"She enjoys swimming, and so ___ her brother.",a:"does",o:["is","has","do"],w:"So + auxiliary + subject. The auxiliary matches the first verb: enjoys, so does."},
{id:"a07",c:"aux",s:"Our teacher ___ to be a professional dancer before she started teaching.",a:"used",o:["would","ought","going"],w:"Used to describes past states. Would cannot be used for states like be."},
{id:"a08",c:"aux",s:"It ___ have been Tom who phoned; he is abroad this week.",a:"cannot",o:["must","should","would"],w:"Cannot have + past participle: you are sure it was impossible."},
{id:"a09",c:"aux",s:"I should ___ listened to your advice.",a:"have",o:["had","be","has"],w:"Should have + past participle: a past regret or mistake."},
{id:"a10",c:"aux",s:"Yesterday we ___ to wait an hour for a table.",a:"had",o:["have","has","must"],w:"The past of have to is had to. Must has no past form."},
{id:"a11",c:"aux",s:"All the players ___ been asked to bring a passport, so please check yours.",a:"have",o:["has","had","are"],w:"Present perfect passive with a plural subject: have been asked."},
{id:"a12",c:"aux",s:"By this time next year, I ___ have lived here for ten years.",a:"will",alt:["shall"],o:["would","am","had"],w:"Future perfect: will have + past participle."},
{id:"a13",c:"aux",s:"Little ___ she know that the exam had been cancelled.",a:"did",o:["has","was","does"],w:"Negative adverbials such as little, never and hardly are followed by inversion with an auxiliary."},
{id:"a14",c:"pron",s:"Nobody showed Tom how to play the guitar, so he taught ___.",a:"himself",o:["him","his","itself"],w:"Reflexive pronoun: the subject and the object are the same person."},
{id:"a15",c:"pron",s:"We really enjoyed ___ at the party.",a:"ourselves",o:["us","our","we"],w:"Enjoy + reflexive pronoun. Watch the plural: ourselves."},
{id:"a16",c:"pron",s:"The two friends have known each ___ for years.",a:"other",o:["another","one","the"],w:"Each other: a reciprocal pronoun."},
{id:"a17",c:"pron",s:"___ was raining so heavily that we stayed indoors.",a:"it",o:["there","that","which"],w:"It is the subject for weather, time and distance."},
{id:"a18",c:"pron",s:"___ used to be a cinema on this street.",a:"there",o:["it","that","they"],w:"There + be introduces something that exists or existed."},
{id:"a19",c:"pron",s:"My phone fell in the sea, so I had to buy a new ___.",a:"one",o:["it","that","other"],w:"One replaces a countable noun when it is a different thing. It would mean the same phone."},
{id:"a20",c:"rel",s:"The museum, ___ opened in 1998, attracts thousands of visitors every year.",a:"which",o:["that","what","who"],w:"After a comma (non-defining clause) use which, not that."},
{id:"a21",c:"rel",s:"The woman to ___ I spoke was very helpful.",a:"whom",o:["who","which","that"],w:"Preposition + whom for people."},
{id:"a22",c:"pron",s:"I could not understand ___ he was saying.",a:"what",o:["which","that","how"],w:"What means the thing that."},
{id:"a23",c:"pron",s:"I felt so ill that I did not eat ___ all day.",a:"anything",o:["something","everything","nothing"],w:"Anything in negative sentences. Nothing would make a double negative."},
{id:"a24",c:"pron",s:"Many students prefer working in groups because it helps ___ to learn from each other.",a:"them",o:["they","their","themselves"],w:"Object pronoun after helps."},
{id:"a25",c:"pron",s:"The city is famous for ___ ancient walls.",a:"its",o:["it's","his","their"],w:"Its, with no apostrophe, is the possessive of it."},
{id:"a26",c:"det",s:"We visited four countries in two weeks, and ___ one was very different.",a:"each",alt:["every"],o:["all","both","other"],w:"Each or every + one, for the items in a group taken separately."},
{id:"a27",c:"det",s:"We have not finished yet, so we need ___ ten minutes.",a:"another",o:["other","more","else"],w:"Another + number + plural noun means that many more."},
{id:"a28",c:"det",s:"Some people prefer cities, while ___ prefer the countryside.",a:"others",alt:["some"],o:["other","another","the"],w:"Others means other people. No noun follows."},
{id:"a29",c:"det",s:"I have two brothers, and ___ of them are doctors, like me.",a:"both",o:["each","either","neither"],w:"Both of + plural pronoun, for two people."},
{id:"a30",c:"det",s:"I spent the ___ weekend revising for the exam.",a:"whole",alt:["entire"],o:["all","every","each"],w:"The whole + singular noun. All would not follow the."},
{id:"a31",c:"det",s:"It rained ___ day yesterday, so we stayed in.",a:"all",o:["every","each","whole"],w:"All day means from morning to night."},
{id:"a32",c:"det",s:"Who is ___ best player in your team?",a:"the",o:["a","an","that"],w:"The before a superlative."},
{id:"a33",c:"det",s:"Hardly ___ people came to the concert, so it was cancelled.",a:"any",o:["some","many","few"],w:"Hardly any means almost none."},
{id:"a34",c:"det",s:"There is not ___ point in complaining about it now.",a:"much",alt:["any"],o:["many","few","lot"],w:"Not much or not any with uncountable nouns."},
{id:"a35",c:"det",s:"I have ___ few friends who live nearby, so I see them quite often.",a:"a",o:["the","some","any"],w:"A few is positive (some). Few alone is negative (hardly any)."},
{id:"a36",c:"det",s:"___ four years, the Olympic Games take place in a different country.",a:"every",o:["all","each","whole"],w:"Every + number + plural noun for regular intervals."},
{id:"a37",c:"det",s:"I have ___ idea what he is talking about.",a:"no",o:["not","any","none"],w:"No idea. Not and none cannot go directly before a noun."}
]);
