/* Open cloze (B2 First Part 2) practice items. Original sentences, grouped by gap type. Drafted, not a verified frequency list: teacher review advised. UK spelling. Answers are one word, no contractions. */
window.CLOZE=[
{id:"p1",c:"prep",s:"She is very good ___ solving puzzles.",a:"at",o:["in","on","for"],w:"Good at + -ing."},
{id:"p2",c:"prep",s:"I am looking forward ___ seeing you next week.",a:"to",o:["for","at","with"],w:"Look forward to + -ing."},
{id:"p3",c:"prep",s:"He apologised ___ being late.",a:"for",o:["of","about","to"],w:"Apologise for."},
{id:"p4",c:"prep",s:"Many students depend ___ their parents for money.",a:"on",o:["of","from","at"],w:"Depend on."},
{id:"p5",c:"prep",s:"The teacher was proud ___ her class.",a:"of",o:["for","about","with"],w:"Proud of."},
{id:"p6",c:"prep",s:"We were surprised ___ the news.",a:"at",alt:["by"],o:["of","for","with"],w:"Surprised at or by."},
{id:"p7",c:"prep",s:"There is no point ___ arguing about it.",a:"in",o:["of","at","for"],w:"No point in + -ing."},
{id:"p8",c:"prep",s:"She is interested ___ learning Japanese.",a:"in",o:["at","on","about"],w:"Interested in."},
{id:"p9",c:"prep",s:"What is the reason ___ this delay?",a:"for",o:["of","to","from"],w:"Reason for."},
{id:"l1",c:"link",s:"___ it was raining, we went for a walk.",a:"although",alt:["though"],o:["despite","however","because"],w:"Although + a full clause."},
{id:"l2",c:"link",s:"We went out ___ the bad weather.",a:"despite",o:["although","however","because"],w:"Despite + a noun phrase. Although needs a clause."},
{id:"l3",c:"link",s:"I will call you as soon ___ I arrive.",a:"as",o:["so","when","than"],w:"As soon as."},
{id:"l4",c:"link",s:"He studied hard in ___ to pass.",a:"order",o:["case","time","need"],w:"In order to."},
{id:"l5",c:"link",s:"She did not go out ___ she had finished her homework.",a:"until",alt:["till"],o:["unless","during","while"],w:"Until gives the time when something changes."},
{id:"l6",c:"link",s:"He is rich; ___, he is not happy.",a:"however",o:["although","despite","therefore"],w:"However links two ideas and takes a comma."},
{id:"l7",c:"link",s:"We will be late ___ we leave now.",a:"unless",o:["if","because","although"],w:"Unless means if not."},
{id:"s1",c:"struct",s:"I wish I ___ more time to study.",a:"had",o:["have","would have","has"],w:"Wish + past tense for a present regret."},
{id:"s2",c:"struct",s:"He was made ___ stay after school.",a:"to",o:["for","by","with"],w:"Passive of make takes a to-infinitive."},
{id:"s3",c:"struct",s:"You ___ better see a doctor about that cough.",a:"had",o:["would","should","could"],w:"Had better + bare infinitive."},
{id:"s4",c:"struct",s:"Not only ___ she win the race, but she also broke the record.",a:"did",o:["has","was","does"],w:"Inversion after not only needs an auxiliary."},
{id:"s5",c:"struct",s:"The window ___ broken last night.",a:"was",o:["has","is","had"],w:"Passive, past simple."},
{id:"s6",c:"struct",s:"He asked me ___ I could help him.",a:"if",alt:["whether"],o:["that","what","so"],w:"Reported yes/no question."},
{id:"r1",c:"rel",s:"The girl ___ sits next to me is my cousin.",a:"who",alt:["that"],o:["whose","which","what"],w:"Who for people as the subject."},
{id:"r2",c:"rel",s:"That is the man ___ car was stolen.",a:"whose",o:["who","which","that"],w:"Whose shows possession."},
{id:"r3",c:"rel",s:"This is the house ___ I grew up.",a:"where",o:["which","what","when"],w:"Where for places."},
{id:"r4",c:"rel",s:"She told me about her trip, ___ sounded amazing.",a:"which",o:["what","who","it"],w:"Which refers back to the whole idea."},
{id:"r5",c:"rel",s:"I will never forget the day ___ we met.",a:"when",alt:["that"],o:["which","where","what"],w:"When for times."},
{id:"q1",c:"quant",s:"There is not ___ milk left in the fridge.",a:"any",o:["some","many","few"],w:"Any in negatives. Milk is uncountable."},
{id:"q2",c:"quant",s:"I have ___ friends in this city, so I feel lonely.",a:"few",o:["little","much","less"],w:"Few + countable nouns, with a negative feeling."},
{id:"q3",c:"quant",s:"How ___ time do we have left?",a:"much",o:["many","few","any"],w:"Much with uncountable nouns."},
{id:"q4",c:"quant",s:"I tried both options, but ___ of them worked.",a:"neither",o:["none","either","both"],w:"Neither is for two things. Watch the spelling: neither."},
{id:"q5",c:"quant",s:"___ of my friends lives near me; they all live far away.",a:"none",o:["neither","any","every"],w:"None is for more than two."},
{id:"q6",c:"quant",s:"She is old ___ to drive.",a:"enough",o:["too","very","so"],w:"Enough comes after the adjective. Watch the spelling: enough."},
{id:"f1",c:"fixed",s:"At first I did not like him, but I got used ___ his jokes.",a:"to",o:["for","with","at"],w:"Get used to + noun or -ing."},
{id:"f2",c:"fixed",s:"I would rather stay home ___ go out tonight.",a:"than",o:["to","that","then"],w:"Would rather ... than. Not then."},
{id:"f3",c:"fixed",s:"As far ___ I know, the shop closes at six.",a:"as",o:["so","long","that"],w:"As far as I know."},
{id:"f4",c:"fixed",s:"She has been working here ___ 2019.",a:"since",o:["for","from","during"],w:"Since + a point in time."},
{id:"f5",c:"fixed",s:"He did it on ___ because he wanted to annoy me.",a:"purpose",o:["accident","intention","aim"],w:"On purpose."},
{id:"v1",c:"pv",s:"I cannot find my keys. Can you help me look ___ them?",a:"for",o:["after","at","up"],w:"Look for means search."},
{id:"v2",c:"pv",s:"The meeting was called ___ because the manager was ill.",a:"off",o:["out","away","over"],w:"Call off means cancel."},
{id:"v3",c:"pv",s:"She grew ___ in a small village.",a:"up",o:["out","over","off"],w:"Grow up."},
{id:"v4",c:"pv",s:"We ran ___ of milk, so I went to the shop.",a:"out",o:["off","away","up"],w:"Run out of."}
];
