/* Part 4 (B2 First key word transformations), set 4: tenses and time, phrasal verbs, fixed expressions, prepositions. Original sentences. Each answer is written as "first half|second half": the two halves are the two marked elements (1 mark each). Drafted, not a verified frequency list: teacher review advised. UK spelling. Needs kwt.js. */
window.KWT=(window.KWT||[]).concat([
{id:"k91",c:"tense",s:"I started learning the guitar five years ago.",k:"BEEN",b:"I",e:"the guitar for five years.",a:["have been|learning"],w:"Present perfect continuous with for."},
{id:"k92",c:"tense",s:"The last time I saw Mia was in 2019.",k:"SEEN",b:"I",e:"Mia since 2019.",a:["have not|seen"],w:"Present perfect negative + since."},
{id:"k93",c:"tense",s:"I have never been to Rome before.",k:"FIRST",b:"This is",e:"to Rome.",a:["my first|visit","my first|trip"],w:"This is my first + noun."},
{id:"k94",c:"tense",s:"They began building the house in March and are still building it.",k:"BEEN",b:"They",e:"the house since March.",a:["have been|building"],w:"Present perfect continuous with since."},
{id:"k95",c:"tense",s:"Lara last called me three weeks ago.",k:"FOR",b:"Lara",e:"three weeks.",a:["has not|called me for","has not|phoned me for","has not|rung me for"],w:"Present perfect negative + for + a period of time."},
{id:"k96",c:"tense",s:"I will text you the moment I get to the airport.",k:"SOON",b:"I will text you",e:"I get to the airport.",a:["as soon|as"],w:"As soon as means the moment that."},
{id:"k97",c:"pv",s:"They cancelled the match because of the storm.",k:"CALLED",b:"They",e:"the match because of the storm.",a:["called|off"],w:"Call off means cancel."},
{id:"k98",c:"pv",s:"I cannot understand why he is so angry.",k:"OUT",b:"I cannot",e:"why he is so angry.",a:["work|out","figure|out"],w:"Work out or figure out means understand or solve."},
{id:"k99",c:"pv",s:"Our plane left the ground at ten o'clock.",k:"OFF",b:"Our plane",e:"at ten o'clock.",a:["took|off"],w:"Take off means leave the ground."},
{id:"k100",c:"pv",s:"I am looking after my neighbour's cat this week.",k:"CARE",b:"I am",e:"my neighbour's cat this week.",a:["taking care|of"],w:"Take care of means look after."},
{id:"k101",c:"pv",s:"We have no more coffee.",k:"RUN",b:"We",e:"coffee.",a:["have run|out of"],w:"Run out of means use all of something."},
{id:"k102",c:"pv",s:"He resembles his grandfather a lot.",k:"AFTER",b:"He",e:"his grandfather.",a:["takes|after"],w:"Take after means resemble a family member."},
{id:"k103",c:"pv",s:"Sara tolerates her brother's loud music without complaining.",k:"PUTS",b:"Sara",e:"her brother's loud music without complaining.",a:["puts up|with"],w:"Put up with means tolerate."},
{id:"k104",c:"pv",s:"Please complete this form before you leave.",k:"FILL",b:"Please",e:"this form before you leave.",a:["fill|in","fill|out"],w:"Fill in or fill out a form."},
{id:"k105",c:"pv",s:"My car stopped working on the motorway.",k:"BROKE",b:"My car",e:"on the motorway.",a:["broke|down"],w:"Break down means stop working."},
{id:"k106",c:"pv",s:"We must try to reduce the amount of plastic we use.",k:"CUT",b:"We must try to",e:"the amount of plastic we use.",a:["cut|down","cut down|on","cut back|on"],w:"Cut down (on) or cut back on means reduce."},
{id:"k107",c:"fixed",s:"It is pointless to try to change her mind.",k:"POINT",b:"There",e:"to change her mind.",a:["is no|point in trying"],w:"There is no point in + -ing."},
{id:"k108",c:"fixed",s:"He did not know that the film had already started.",k:"IDEA",b:"He",e:"that the film had already started.",a:["had no|idea"],w:"Have no idea means not know."},
{id:"k109",c:"fixed",s:"Please be patient; it will only take a moment.",k:"BEAR",b:"Please",e:"me; it will only take a moment.",a:["bear|with"],w:"Bear with me means please wait patiently."},
{id:"k110",c:"fixed",s:"Do not arrive late for the nine o'clock meeting.",k:"TIME",b:"Make sure you arrive",e:"for the nine o'clock meeting.",a:["on|time"],w:"On time means at the arranged time, not late."},
{id:"k111",c:"fixed",s:"I did not mean to break your phone.",k:"PURPOSE",b:"I did not break your phone",e:".",a:["on|purpose"],w:"On purpose means deliberately."},
{id:"k112",c:"fixed",s:"You must make the decision yourself.",k:"UP",b:"It",e:"you.",a:["is up|to"],w:"It is up to you means it is your decision."},
{id:"k113",c:"fixed",s:"I think the new rules are unfair.",k:"VIEW",b:"In",e:", the new rules are unfair.",a:["my|view","my point|of view"],w:"In my view means in my opinion."},
{id:"k114",c:"fixed",s:"We must decide quickly because we have almost no time left.",k:"RUNNING",b:"We must decide quickly because time",e:".",a:["is running|out","is running|short"],w:"Time is running out means there is little time left."},
{id:"k115",c:"prep",s:"I am not very interested in sport.",k:"INTEREST",b:"I have",e:"sport.",a:["little|interest in","no|interest in","not much|interest in"],w:"Interest in + noun."},
{id:"k116",c:"prep",s:"The police suspect that he stole the paintings.",k:"SUSPECTED",b:"He",e:"stealing the paintings.",a:["is suspected|of"],w:"Suspect someone of + -ing."},
{id:"k117",c:"prep",s:"The children were very excited about the trip.",k:"LOOKING",b:"The children were",e:"to the trip.",a:["looking|forward"],w:"Look forward to + noun."},
{id:"k118",c:"prep",s:"You cannot rely on him because he never keeps his promises.",k:"DEPEND",b:"You",e:"him because he never keeps his promises.",a:["cannot|depend on","can not|depend on"],w:"Depend on + noun."},
{id:"k119",c:"prep",s:"Karen is fond of jazz.",k:"KEEN",b:"Karen",e:"jazz.",a:["is keen|on"],w:"Keen on + noun."},
{id:"k120",c:"prep",s:"The flights were delayed because of the strike.",k:"ACCOUNT",b:"The flights were delayed",e:"the strike.",a:["on|account of"],w:"On account of means because of."}
]);
