/* Part 1 traps, batch 2 (Cambridge-style, B2-C1). Original sentences. Answers are mine: teacher review advised. UK spelling. Load after part1.js. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"u1",p:1,c:"prep",s:"Her success was entirely due ___ hard work.",a:"to",o:["for","of","by"],w:"Due to."},
{id:"u2",p:1,c:"prep",s:"I would not dream ___ asking him for money.",a:"of",o:["on","to","for"],w:"Dream of + -ing."},
{id:"u3",p:1,c:"prep",s:"He was accused ___ stealing the money.",a:"of",o:["for","with","about"],w:"Accuse someone of."},
{id:"u4",p:1,c:"prep",s:"The company is incapable ___ meeting the deadline.",a:"of",o:["to","for","from"],w:"Incapable of + -ing."},
{id:"u5",p:1,c:"prep",s:"This book is very similar ___ the first one.",a:"to",o:["with","as","than"],w:"Similar to."},
{id:"u6",p:1,c:"prep",s:"He succeeded ___ passing the test at the second attempt.",a:"in",o:["at","on","to"],w:"Succeed in + -ing."},
{id:"u7",p:1,c:"prep",s:"The school has a reputation ___ high standards.",a:"for",o:["to","by","at"],w:"A reputation for."},
{id:"u8",p:1,c:"colloc",s:"She made a real ___ about the delay.",a:"fuss",o:["noise","riot","quarrel"],w:"Make a fuss about."},
{id:"u9",p:1,c:"colloc",s:"He lost his ___ and shouted at the waiter.",a:"temper",o:["temperature","tempo","tension"],w:"Lose your temper."},
{id:"u10",p:1,c:"colloc",s:"The two companies decided to join ___.",a:"forces",o:["ties","teams","strengths"],w:"Join forces."},
{id:"u11",p:1,c:"colloc",s:"There was a ___ of applause when she finished.",a:"round",o:["row","circle","ring"],w:"A round of applause."},
{id:"u12",p:1,c:"colloc",s:"The rumour was entirely without ___.",a:"foundation",o:["found","founder","foundry"],w:"Without foundation = not based on facts."},
{id:"u13",p:1,c:"colloc",s:"A wide ___ of opinions was expressed at the meeting.",a:"range",o:["width","scale","extent"],w:"A range of."},
{id:"u14",p:1,c:"colloc",s:"I had a ___ feeling that something was wrong.",a:"nagging",o:["nagged","nags","nag"],w:"A nagging feeling = one that will not go away."},
{id:"u15",p:1,c:"colloc",s:"The problem is far ___ simple.",a:"from",o:["away","off","beyond"],w:"Far from + adjective = not at all."},
{id:"u16",p:1,c:"colloc",s:"The team is ___ to win the league this year.",a:"tipped",o:["tapped","tilted","tripped"],w:"Tipped to win = expected to win."},
{id:"u17",p:1,c:"colloc",s:"The plan was ___ to failure from the start.",a:"doomed",o:["damaged","deserted","dedicated"],w:"Doomed to failure."},
{id:"u18",p:1,c:"colloc",s:"The exhibition ___ from May to June.",a:"runs",o:["stands","goes","walks"],w:"An event runs for a period."},
{id:"u19",p:1,c:"colloc",s:"She is very ___ about her success and never boasts.",a:"modest",o:["moderate","minor","meagre"],w:"Modest = not boastful."},
{id:"u20",p:1,c:"colloc",s:"Sales have fallen well ___ of expectations.",a:"short",o:["far","low","behind"],w:"Fall short of."},
{id:"u21",p:1,c:"colloc",s:"He works hardest at night; he is at his ___ after midnight.",a:"best",o:["most","better","good"],w:"At your best."},
{id:"u22",p:1,c:"colloc",s:"Be on your best ___ when the inspector visits.",a:"behaviour",o:["manner","conduct","attitude"],w:"On your best behaviour."},
{id:"u23",p:1,c:"pv",s:"I cannot work ___ how to use this machine.",a:"out",o:["off","up","over"],w:"Work out = find the answer."},
{id:"u24",p:1,c:"pv",s:"The shop went ___ of business last year.",a:"out",o:["off","away","under"],w:"Go out of business."},
{id:"u25",p:1,c:"pv",s:"I ran ___ an old friend in the supermarket.",a:"into",o:["after","onto","up"],w:"Run into = meet by chance."},
{id:"u26",p:1,c:"pv",s:"Please look me ___ when you are in town.",a:"up",o:["out","over","after"],w:"Look someone up = visit them."},
{id:"u27",p:1,c:"vocab",s:"The pupil was ___ from school for a week for bad behaviour.",a:"suspended",o:["stopped","cut","missed"],w:"Suspend = stop for a time as a punishment."},
{id:"u28",p:1,c:"vocab",s:"She was ___ to tears by the sad film.",a:"moved",o:["carried","pushed","lifted"],w:"Moved to tears."},
{id:"u29",p:1,c:"vocab",s:"I was under the ___ that the meeting had been cancelled.",a:"impression",o:["impress","impressed","impressive"],w:"Under the impression that."},
{id:"u30",p:1,c:"vocab",s:"The politician was accused of trying to ___ the truth.",a:"bend",o:["fold","curve","turn"],w:"Bend the truth."},
{id:"u31",p:1,c:"vocab",s:"The weather ___ for tomorrow is excellent.",a:"forecast",o:["foresight","forewarning","foretelling"],w:"A weather forecast."},
{id:"u32",p:1,c:"vocab",s:"He ___ that he had ever met the woman before.",a:"denied",o:["ignored","refused","rejected"],w:"Deny that."},
{id:"u33",p:1,c:"vocab",s:"The committee ___ down the proposal.",a:"turned",o:["opposed","refused","denied"],w:"Turn down = refuse."},
{id:"u34",p:1,c:"vocab",s:"I am afraid I must ___ your offer; I have already accepted another job.",a:"decline",o:["deny","deflect","delay"],w:"Decline = politely refuse."},
{id:"u35",p:1,c:"vocab",s:"The company has been ___ by financial problems for years.",a:"plagued",o:["plucked","plugged","plaqued"],w:"Plagued by = troubled again and again."},
{id:"u36",p:1,c:"vocab",s:"Her remarks were widely ___ as a criticism of the manager.",a:"interpreted",o:["translated","explained","declared"],w:"Interpret as."},
{id:"u37",p:1,c:"vocab",s:"Everyone was ___ by the sudden loud bang.",a:"startled",o:["stared","started","startling"],w:"Startled = surprised and a little frightened."},
{id:"u38",p:1,c:"vocab",s:"The candidate was ___ by the panel's tough questions.",a:"unnerved",o:["unleashed","unearthed","unravelled"],w:"Unnerved = made nervous."},
{id:"u39",p:1,c:"vocab",s:"The council meeting was very badly ___.",a:"run",o:["controlled","commanded","governed"],w:"A meeting or business is run."},
{id:"u40",p:1,c:"vocab",s:"Please accept my ___ for missing the meeting.",a:"apologies",o:["excuses","pardon","forgiveness"],w:"Accept my apologies."},
{id:"u41",p:1,c:"struct",s:"___ as it may seem, I actually enjoyed the exam.",a:"strange",o:["strangely","stranger","strangeness"],w:"Adjective + as it may seem."},
{id:"u42",p:1,c:"struct",s:"Were it not ___ the storm, we would have arrived on time.",a:"for",o:["because","due","that"],w:"Were it not for = without."},
{id:"u43",p:1,c:"struct",s:"I would rather you ___ more respect.",a:"showed",o:["show","shows","showing"],w:"Would rather + person + past tense."},
{id:"u44",p:1,c:"struct",s:"It is high time the council ___ something about the roads.",a:"did",o:["does","will do","has done"],w:"It is high time + past tense."},
{id:"u45",p:1,c:"struct",s:"Try as he ___, he could not open the jar.",a:"might",o:["can","must","was"],w:"Try as he might = however hard he tried."},
{id:"u46",p:1,c:"struct",s:"Should you ___ any difficulties, contact us at once.",a:"experience",o:["experienced","experiencing","will experience"],w:"Should + bare infinitive replaces if."},
{id:"u47",p:1,c:"struct",s:"The suspect denied ___ anything about the missing money.",a:"knowing",o:["known","know","to know"],w:"Deny + -ing."},
{id:"u48",p:1,c:"struct",s:"The report is said ___ have been leaked before publication.",a:"to",o:["that","for","of"],w:"Is said to have + past participle."}
]);
