/* Part 1 traps, batch 4 (Cambridge-style, B2-C1). Original sentences. Answers are mine: teacher review advised. UK spelling. Load after part1c.js. Keep file order: numbered tests are cut from this order. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"d1",p:1,c:"colloc",s:"Bad ___ are hard to break once they have formed.",a:"habits",o:["means","methods","procedures"],w:"Break a habit."},
{id:"d2",p:1,c:"link",s:"___ repeated warnings, thousands of people stayed in their homes.",a:"Despite",o:["Whereas","Since","Although"],w:"Despite + noun phrase."},
{id:"d3",p:1,c:"vocab",s:"The film, ___ on a small budget, earned millions.",a:"produced",o:["built","done","shaped"],w:"A film is produced or made."},
{id:"d4",p:1,c:"colloc",s:"The explorers crossed a ___ and empty desert.",a:"vast",o:["whole","high","complete"],w:"Vast = extremely large."},
{id:"d5",p:1,c:"vocab",s:"The forest ___ for miles in every direction.",a:"stretches",o:["lifts","grows","raises"],w:"Stretch = extend over an area."},
{id:"d6",p:1,c:"colloc",s:"As a direct ___ of the storm, schools were closed.",a:"result",o:["conclusion","reason","cause"],w:"As a result of."},
{id:"d7",p:1,c:"colloc",s:"There is hardly enough ___ in the boot for one bag.",a:"room",o:["interval","range","extent"],w:"Room = space."},
{id:"d8",p:1,c:"colloc",s:"Visitors must walk with ___ feet in the temple.",a:"bare",o:["free","clear","open"],w:"Bare feet."},
{id:"d9",p:1,c:"colloc",s:"You must not exceed the agreed spending ___.",a:"limit",o:["lip","edge","outline"],w:"A spending limit."},
{id:"d10",p:1,c:"colloc",s:"After the long coach trip she had a ___ neck.",a:"stiff",o:["fixed","steady","firm"],w:"A stiff neck."},
{id:"d11",p:1,c:"struct",s:"We need to ___ the car serviced before the trip.",a:"get",o:["let","enable","make"],w:"Get or have something done."},
{id:"d12",p:1,c:"colloc",s:"Few people subscribe to that sports ___.",a:"channel",o:["life","world","area"],w:"A TV channel."},
{id:"d13",p:1,c:"vocab",s:"The waiter ___ the table with clean silverware.",a:"set",o:["established","founded","placed"],w:"Set the table."},
{id:"d14",p:1,c:"colloc",s:"The tools date from the Bronze ___.",a:"Age",o:["date","phase","time"],w:"The Bronze Age."},
{id:"d15",p:1,c:"link",s:"He has not decided ___ to accept the job.",a:"whether",o:["so","despite","if"],w:"Whether + to-infinitive."},
{id:"d16",p:1,c:"pv",s:"In the middle of the night, the alarm ___ off.",a:"went",o:["broke","set","burst"],w:"An alarm goes off."},
{id:"d17",p:1,c:"colloc",s:"The delays were ___ due to staff shortages.",a:"largely",o:["badly","extremely","highly"],w:"Largely = mostly."},
{id:"d18",p:1,c:"vocab",s:"He quietly ___ out of the room during the speech.",a:"slipped",o:["chopped","cut","dipped"],w:"Slip out = leave quietly."},
{id:"d19",p:1,c:"vocab",s:"Unemployment has ___ for the third month in a row.",a:"fallen",o:["descended","shortened","subtracted"],w:"Figures fall or rise."},
{id:"d20",p:1,c:"vocab",s:"The team has ___ its efforts on cutting costs.",a:"concentrated",o:["thought","engaged","occupied"],w:"Concentrate on."},
{id:"d21",p:1,c:"colloc",s:"There will be a ___ announcement on Monday.",a:"further",o:["greater","higher","bigger"],w:"A further announcement = another one."},
{id:"d22",p:1,c:"vocab",s:"The ticket price ___ all meals.",a:"includes",o:["consists","features","composes"],w:"Include = have as a part."},
{id:"d23",p:1,c:"vocab",s:"Cost is only one ___ of the problem.",a:"aspect",o:["arrival","appearance","presence"],w:"An aspect of."},
{id:"d24",p:1,c:"link",s:"He kept working, ___ though he felt ill.",a:"even",o:["still","however","whereas"],w:"Even though."},
{id:"d25",p:1,c:"vocab",s:"The workers chose a ___ to speak for them.",a:"representative",o:["sample","model","style"],w:"A representative speaks for others."},
{id:"d26",p:1,c:"prep",s:"She is widely known ___ the best chef in town.",a:"as",o:["by","over","about"],w:"Known as = called or regarded as."},
{id:"d27",p:1,c:"vocab",s:"The current world record ___ is training in Berlin.",a:"holder",o:["owner","occupier","keeper"],w:"Record holder."},
{id:"d28",p:1,c:"vocab",s:"At the party, my aunt ___ me to her new neighbour.",a:"introduced",o:["begun","taught","explained"],w:"Introduce someone to someone."},
{id:"d29",p:1,c:"vocab",s:"We were ___ to find seats on the last train.",a:"fortunate",o:["reasonable","appropriate","suitable"],w:"Fortunate = lucky."},
{id:"d30",p:1,c:"colloc",s:"A regular bus ___ links the village to the town.",a:"service",o:["scheme","design","pattern"],w:"A bus service."},
{id:"d31",p:1,c:"colloc",s:"The bank lent them a large ___ of money.",a:"sum",o:["number","total","figure"],w:"A sum of money."},
{id:"d32",p:1,c:"vocab",s:"It ___ years of practice to play like that.",a:"takes",o:["wants","uses","asks"],w:"It takes time."},
{id:"d33",p:1,c:"colloc",s:"This bus ___ passes through three villages.",a:"route",o:["path","way","lane"],w:"A bus route."},
{id:"d34",p:1,c:"vocab",s:"In a fire, the most important thing is not to ___.",a:"panic",o:["scare","shock","frighten"],w:"Panic has no object."},
{id:"d35",p:1,c:"colloc",s:"There is another ___ to the story.",a:"side",o:["part","half","area"],w:"Another side to the story."},
{id:"d36",p:1,c:"vocab",s:"This path will ___ you to a quiet beach.",a:"lead",o:["head","move","proceed"],w:"A path leads you somewhere."},
{id:"d37",p:1,c:"vocab",s:"Only two minutes were ___ before the deadline.",a:"remaining",o:["staying","resting","waiting"],w:"Remaining = left."},
{id:"d38",p:1,c:"struct",s:"Visitors are not ___ to feed the animals.",a:"supposed",o:["wondered","judged","doubted"],w:"Not supposed to = not allowed to."},
{id:"d39",p:1,c:"colloc",s:"The wedding will ___ place in June.",a:"take",o:["hold","get","end"],w:"Take place = happen."},
{id:"d40",p:1,c:"vocab",s:"The film is loosely ___ on a true story.",a:"based",o:["located","settled","formed"],w:"Based on."},
{id:"d41",p:1,c:"vocab",s:"The ___ of blood makes him feel faint.",a:"sight",o:["vision","view","outlook"],w:"The sight of something."},
{id:"d42",p:1,c:"colloc",s:"The customer is ___ an order for fifty units.",a:"placing",o:["producing","forming","making"],w:"Place an order."},
{id:"d43",p:1,c:"vocab",s:"I am afraid this coat no longer ___ me.",a:"fits",o:["contains","holds","sits"],w:"Clothes fit you."},
{id:"d44",p:1,c:"struct",s:"You ___ not to have told him my secret.",a:"ought",o:["can","need","may"],w:"Ought not to have + past participle."}
]);
