/* Part 1 traps (Cambridge-style, B2-C1). Original sentences written to test commonly confused points: dependent prepositions, collocations, phrasal verbs, confusable words and tricky structures. Answers are mine: teacher review advised. UK spelling. Load after cloze.js. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"t1",p:1,c:"prep",s:"Our coach is a stickler ___ good timekeeping.",a:"for",o:["in","of","on"],w:"A stickler for something."},
{id:"t2",p:1,c:"prep",s:"Some people are prone ___ colds in winter.",a:"to",o:["for","of","with"],w:"Prone to."},
{id:"t3",p:1,c:"prep",s:"The results are consistent ___ our earlier findings.",a:"with",o:["to","of","for"],w:"Consistent with."},
{id:"t4",p:1,c:"prep",s:"The firm prides itself ___ its fast delivery.",a:"on",o:["for","in","with"],w:"Pride oneself on."},
{id:"t5",p:1,c:"prep",s:"He has no objection ___ the new timetable.",a:"to",o:["with","for","at"],w:"Objection to."},
{id:"t6",p:1,c:"prep",s:"Is she really capable ___ running the whole department?",a:"of",o:["to","for","in"],w:"Capable of + -ing."},
{id:"t7",p:1,c:"prep",s:"My brother is allergic ___ nuts.",a:"to",o:["with","of","from"],w:"Allergic to."},
{id:"t8",p:1,c:"prep",s:"She is very keen ___ cycling.",a:"on",o:["at","for","in"],w:"Keen on."},
{id:"t9",p:1,c:"colloc",s:"She drives a hard ___ in every negotiation.",a:"bargain",o:["sale","purchase","price"],w:"Drive a hard bargain."},
{id:"t10",p:1,c:"colloc",s:"Do not jump ___ conclusions before you have heard the facts.",a:"to",o:["at","into","over"],w:"Jump to conclusions."},
{id:"t11",p:1,c:"colloc",s:"The scandal ___ the reputation of the whole club.",a:"tarnished",o:["twisted","tackled","tilted"],w:"Tarnish a reputation."},
{id:"t12",p:1,c:"colloc",s:"He has a real flair ___ languages.",a:"for",o:["of","to","at"],w:"A flair for."},
{id:"t13",p:1,c:"colloc",s:"The new musical received rave ___ from the critics.",a:"reviews",o:["revues","reveries","revisions"],w:"Rave reviews. A revue is a type of show."},
{id:"t14",p:1,c:"colloc",s:"This job needs a wealth ___ experience.",a:"of",o:["in","for","with"],w:"A wealth of."},
{id:"t15",p:1,c:"colloc",s:"By no ___ is the work finished.",a:"means",o:["way","reason","chance"],w:"By no means = not at all."},
{id:"t16",p:1,c:"colloc",s:"In the event ___ a delay, we will send you an email.",a:"of",o:["for","to","in"],w:"In the event of."},
{id:"t17",p:1,c:"colloc",s:"By and ___, the new system works well.",a:"large",o:["wide","big","broad"],w:"By and large = mostly."},
{id:"t18",p:1,c:"colloc",s:"They live from hand to ___ on very low wages.",a:"mouth",o:["pocket","stomach","month"],w:"Live from hand to mouth."},
{id:"t19",p:1,c:"colloc",s:"He took the bad news in his ___ and carried on working.",a:"stride",o:["step","pace","walk"],w:"Take something in your stride."},
{id:"t20",p:1,c:"colloc",s:"I would like to ___ my sincere thanks to the volunteers.",a:"extend",o:["expand","stretch","spread"],w:"Extend thanks."},
{id:"t21",p:1,c:"pv",s:"The police have not ___ out a criminal motive.",a:"ruled",o:["put","taken","turned"],w:"Rule out = decide something is not possible."},
{id:"t22",p:1,c:"pv",s:"You must come to ___ with the fact that she has left.",a:"terms",o:["agreement","peace","conclusion"],w:"Come to terms with."},
{id:"t23",p:1,c:"pv",s:"Let us put our differences ___ and work together.",a:"aside",o:["off","out","down"],w:"Put aside."},
{id:"t24",p:1,c:"pv",s:"The manager finally gave ___ to the staff's demands.",a:"in",o:["up","out","off"],w:"Give in to."},
{id:"t25",p:1,c:"pv",s:"The talks ground to a ___ after the first week.",a:"halt",o:["pause","close","finish"],w:"Grind to a halt."},
{id:"t26",p:1,c:"pv",s:"Tickets for the concert were snapped ___ within an hour.",a:"up",o:["down","over","in"],w:"Snap up = buy quickly."},
{id:"t27",p:1,c:"pv",s:"The deal fell ___ at the last minute.",a:"through",o:["over","away","off"],w:"Fall through = fail to happen."},
{id:"t28",p:1,c:"pv",s:"It took her weeks to get ___ the shock.",a:"over",o:["through","across","by"],w:"Get over = recover from."},
{id:"t29",p:1,c:"pv",s:"Half the class have gone ___ with flu.",a:"down",o:["up","off","out"],w:"Go down with an illness."},
{id:"t30",p:1,c:"pv",s:"I cannot put ___ with this noise any longer.",a:"up",o:["on","off","out"],w:"Put up with = tolerate."},
{id:"t31",p:1,c:"vocab",s:"A calm word from the teacher helped to ___ the situation.",a:"defuse",o:["diffuse","defer","defend"],w:"Defuse = make less dangerous. Not diffuse."},
{id:"t32",p:1,c:"vocab",s:"It was a ___ decision, made without any thought.",a:"rash",o:["rapid","raw","rare"],w:"Rash = done too quickly without thinking."},
{id:"t33",p:1,c:"vocab",s:"Heavy snow ___ us from leaving the village.",a:"prevented",o:["avoided","forbade","protected"],w:"Prevent someone from doing something."},
{id:"t34",p:1,c:"vocab",s:"He is very ___ about his weight and never discusses it.",a:"sensitive",o:["sensible","sensed","sensory"],w:"Sensitive = easily upset. Sensible = practical."},
{id:"t35",p:1,c:"vocab",s:"Experts ___ the accident to a faulty brake.",a:"attributed",o:["blamed","accused","charged"],w:"Attribute something to. Blame needs on, and accuse needs of."},
{id:"t36",p:1,c:"vocab",s:"The jury found the man ___ of fraud.",a:"guilty",o:["accused","charged","criminal"],w:"Found guilty. A person is accused or charged before the trial."},
{id:"t37",p:1,c:"vocab",s:"Could you ___ me five pounds until tomorrow?",a:"lend",o:["borrow","owe","lease"],w:"Lend = give for a time. Borrow = take for a time."},
{id:"t38",p:1,c:"vocab",s:"The manager was under great ___ to resign.",a:"pressure",o:["tension","strain","force"],w:"Pressure to do something."},
{id:"t39",p:1,c:"vocab",s:"Despite early setbacks, the launch was a ___ success.",a:"resounding",o:["sounding","deafening","thundering"],w:"Resounding success."},
{id:"t40",p:1,c:"vocab",s:"They were ___ to the fact that prices had risen.",a:"oblivious",o:["obscure","obsessed","obvious"],w:"Oblivious to = not aware of."},
{id:"t41",p:1,c:"link",s:"You can use my car ___ you drive carefully.",a:"provided",alt:["providing"],o:["although","unless","whereas"],w:"Provided that = on condition that."},
{id:"t42",p:1,c:"struct",s:"Not until the results came out ___ people realise how serious it was.",a:"did",o:["had","were","do"],w:"Inversion after not until."},
{id:"t43",p:1,c:"link",s:"No sooner had we left ___ it began to rain.",a:"than",o:["when","that","then"],w:"No sooner ... than."},
{id:"t44",p:1,c:"link",s:"Scarcely had we arrived ___ the show began.",a:"when",alt:["before"],o:["than","that","then"],w:"Scarcely ... when. No sooner takes than."}
]);
