/* Part 4 (B2 First key word transformations), set 2: conditionals, wish and unreal past, modals. Original sentences. Each answer is written as "first half|second half": the two halves are the two marked elements (1 mark each). Drafted, not a verified frequency list: teacher review advised. UK spelling. Needs kwt.js. */
window.KWT=(window.KWT||[]).concat([
{id:"k31",c:"cond",s:"You can only enter the lab if you have a pass.",k:"UNLESS",b:"You cannot enter the lab",e:"a pass.",a:["unless you|have"],w:"Unless means if not, so the verb after it is positive in form."},
{id:"k32",c:"cond",s:"I would like to travel more, but I have not got enough money.",k:"IF",b:"I would travel more",e:"more money.",a:["if I|had"],w:"Second conditional: if + past simple."},
{id:"k33",c:"cond",s:"We did not take a map, so we got lost.",k:"HAD",b:"If we",e:"a map, we would not have got lost.",a:["had|taken"],w:"Third conditional: if + past perfect."},
{id:"k34",c:"cond",s:"She did not revise, so she failed the test.",k:"WOULD",b:"If she had revised,",e:"the test.",a:["she would|have passed","she would|not have failed"],w:"Third conditional result clause: would have + past participle."},
{id:"k35",c:"cond",s:"Take an umbrella because it may rain later.",k:"CASE",b:"Take an umbrella",e:"later.",a:["in case|it rains","in case|it should rain"],w:"In case + present simple, as a precaution."},
{id:"k36",c:"cond",s:"You can borrow my laptop if you promise to be careful.",k:"LONG",b:"You can borrow my laptop",e:"careful.",a:["as long|as you are"],w:"As long as means on condition that."},
{id:"k37",c:"cond",s:"I do not know the answer, so I cannot tell you.",k:"KNEW",b:"If",e:"the answer, I would tell you.",a:["I|knew"],w:"Second conditional: if + past simple."},
{id:"k38",c:"cond",s:"I would have failed without your help.",k:"FOR",b:"If",e:"your help, I would have failed.",a:["it had not|been for"],w:"If it had not been for means without (third conditional)."},
{id:"k39",c:"cond",s:"Maybe it will rain, and then the match will be cancelled.",k:"IF",b:"The match will be cancelled",e:".",a:["if it|rains","if it|does rain"],w:"First conditional: if + present simple."},
{id:"k40",c:"cond",s:"I would go to the party, but I am working tomorrow.",k:"WERE",b:"I would go to the party",e:"working tomorrow.",a:["if I|were not"],w:"Second conditional with be: were for all persons."},
{id:"k41",c:"wish",s:"I regret not studying medicine at university.",k:"WISH",b:"I",e:"studied medicine at university.",a:["wish I|had"],w:"Wish + past perfect for a regret about the past."},
{id:"k42",c:"wish",s:"It is a pity you cannot come to the party.",k:"WISH",b:"I",e:"come to the party.",a:["wish you|could"],w:"Wish + could for something you want to be possible now."},
{id:"k43",c:"wish",s:"I would prefer you not to smoke in here.",k:"RATHER",b:"I",e:"smoke in here.",a:["would rather|you did not"],w:"Would rather + someone + past simple for a present preference."},
{id:"k44",c:"wish",s:"Tom is sorry that he did not apologise to Mia.",k:"ONLY",b:"Tom thinks, 'If",e:"apologised to Mia.'",a:["only I|had"],w:"If only + past perfect expresses a strong regret."},
{id:"k45",c:"wish",s:"I am annoyed that my neighbours play loud music every night.",k:"STOP",b:"I wish my neighbours",e:"loud music every night.",a:["would stop|playing"],w:"Wish + would for an annoying habit."},
{id:"k46",c:"wish",s:"You should go to bed now; it is late.",k:"TIME",b:"It",e:"to bed.",a:["is time|you went","is high time|you went","is about time|you went"],w:"It is time + subject + past simple."},
{id:"k47",c:"wish",s:"He regrets selling his guitar.",k:"WISHES",b:"He",e:"sold his guitar.",a:["wishes he|had not","wishes he|had never"],w:"Wish + past perfect for a past regret."},
{id:"k48",c:"wish",s:"She does not live near the sea, and she would love to.",k:"WISHES",b:"She",e:"near the sea.",a:["wishes she|lived","wishes she|could live"],w:"Wish + past simple for an unreal present situation."},
{id:"k49",c:"modal",s:"It is not necessary for you to bring any food.",k:"NEED",b:"You",e:"any food.",a:["do not|need to bring","need not|bring"],w:"Do not need to or need not: no obligation."},
{id:"k50",c:"modal",s:"Perhaps he missed the bus.",k:"MAY",b:"He",e:"the bus.",a:["may have|missed"],w:"May have + past participle: a possibility about the past."},
{id:"k51",c:"modal",s:"It is impossible that Ellie took your keys because she was not here.",k:"CANNOT",b:"Ellie",e:"your keys because she was not here.",a:["cannot have|taken"],w:"Cannot have + past participle: certain it did not happen."},
{id:"k52",c:"modal",s:"It was wrong of you not to tell me earlier.",k:"SHOULD",b:"You",e:"me earlier.",a:["should have|told"],w:"Should have + past participle: criticism of a past action."},
{id:"k53",c:"modal",s:"It was not necessary for us to hurry because the train was late.",k:"NEED",b:"We",e:"because the train was late.",a:["did not|need to hurry"],w:"Did not need to + infinitive: it was not necessary."},
{id:"k54",c:"modal",s:"I am sure that she is exhausted after the long trip.",k:"MUST",b:"She",e:"exhausted after the long trip.",a:["must|be"],w:"Must + be for a logical deduction about the present."},
{id:"k55",c:"modal",s:"Is it all right if I use your phone?",k:"MAY",b:"",e:"your phone?",a:["may I|use"],w:"May I + infinitive: a polite request."},
{id:"k56",c:"modal",s:"You are not allowed to park here.",k:"MUST",b:"You",e:"here.",a:["must not|park"],w:"Must not expresses a prohibition."},
{id:"k57",c:"modal",s:"I think it would be a good idea for you to speak to your manager.",k:"BETTER",b:"You",e:"speak to your manager.",a:["had|better"],w:"Had better + bare infinitive: strong advice."},
{id:"k58",c:"modal",s:"Perhaps Jack will win the competition, but I doubt it.",k:"MIGHT",b:"Jack",e:"the competition, but I doubt it.",a:["might|win"],w:"Might + bare infinitive: a weak possibility."},
{id:"k59",c:"modal",s:"She was able to swim when she was only three.",k:"COULD",b:"She",e:"when she was only three.",a:["could|swim"],w:"Could for general ability in the past."},
{id:"k60",c:"modal",s:"I was forced to leave early because of the storm.",k:"HAD",b:"I",e:"early because of the storm.",a:["had to|leave"],w:"Had to for obligation in the past."}
]);
