/* Part 4 (B2 First key word transformations), set 3: comparison, so/such/too/enough, verb patterns, linkers and relatives. Original sentences. Each answer is written as "first half|second half": the two halves are the two marked elements (1 mark each). Drafted, not a verified frequency list: teacher review advised. UK spelling. Needs kwt.js. */
window.KWT=(window.KWT||[]).concat([
{id:"k61",c:"comp",s:"No other student in the class is as clever as Maria.",k:"CLEVEREST",b:"Maria is",e:"in the class.",a:["the cleverest|student","the|cleverest"],w:"Superlative: the + adjective + -est."},
{id:"k62",c:"comp",s:"My brother is 1.80 metres tall and I am 1.75 metres tall.",k:"AS",b:"I",e:"my brother.",a:["am not|as tall as"],w:"Not as + adjective + as."},
{id:"k63",c:"comp",s:"The hotel was cheaper than I expected.",k:"EXPENSIVE",b:"The hotel was",e:"I expected.",a:["not as|expensive as","not so|expensive as","less|expensive than"],w:"Not as ... as is the same as less ... than."},
{id:"k64",c:"comp",s:"I have never watched such a boring film.",k:"MOST",b:"This is",e:"I have ever watched.",a:["the most|boring film"],w:"Superlative of a long adjective: the most + adjective."},
{id:"k65",c:"comp",s:"As you practise more, your pronunciation gets better.",k:"MORE",b:"The",e:", the better your pronunciation gets.",a:["more you|practise"],w:"The + comparative, the + comparative."},
{id:"k66",c:"comp",s:"Anna's flat is slightly smaller than Pia's.",k:"QUITE",b:"Anna's flat is",e:"Pia's.",a:["not quite|as big as","not quite|as large as"],w:"Not quite as ... as means slightly less than."},
{id:"k67",c:"comp",s:"Nobody in the office works harder than Hana.",k:"HARDEST",b:"Hana is",e:"in the office.",a:["the hardest|worker"],w:"Superlative: the hardest worker."},
{id:"k68",c:"comp",s:"My room is twelve square metres and hers is twenty-four.",k:"TWICE",b:"Her room is",e:"mine.",a:["twice as|big as","twice as|large as"],w:"Twice as + adjective + as."},
{id:"k69",c:"degree",s:"The soup was so hot that I could not eat it.",k:"TOO",b:"The soup",e:"eat.",a:["was too|hot to"],w:"Too + adjective + to-infinitive."},
{id:"k70",c:"degree",s:"The room was not big enough for all of us.",k:"SMALL",b:"The room",e:"all of us.",a:["was too|small for"],w:"Too + adjective + for: the opposite of not enough."},
{id:"k71",c:"degree",s:"It was such a long queue that we gave up.",k:"SO",b:"The queue",e:"we gave up.",a:["was so|long that"],w:"So + adjective + that."},
{id:"k72",c:"degree",s:"The weather was so awful that we stayed indoors.",k:"SUCH",b:"It",e:"we stayed indoors.",a:["was such|awful weather that"],w:"Such + adjective + uncountable noun + that."},
{id:"k73",c:"degree",s:"There is not enough time to see the whole museum.",k:"ENOUGH",b:"We do not have",e:"the whole museum.",a:["enough time|to see"],w:"Enough comes before a noun."},
{id:"k74",c:"degree",s:"She is too young to vote.",k:"OLD",b:"She",e:"to vote.",a:["is not|old enough"],w:"Not old enough means too young."},
{id:"k75",c:"degree",s:"The speaker was so boring that I fell asleep.",k:"SUCH",b:"It was",e:"I fell asleep.",a:["such a|boring speaker that"],w:"Such + a + adjective + countable noun + that."},
{id:"k76",c:"degree",s:"It was warm enough to swim in the lake.",k:"SO",b:"It was",e:"we swam in the lake.",a:["so warm|that"],w:"So + adjective + that + result."},
{id:"k77",c:"vpat",s:"She stopped smoking last year.",k:"GAVE",b:"She",e:"last year.",a:["gave up|smoking"],w:"Give up + -ing."},
{id:"k78",c:"vpat",s:"Remember to post the letter.",k:"FORGET",b:"Do not",e:"the letter.",a:["forget to|post"],w:"Forget + to-infinitive."},
{id:"k79",c:"vpat",s:"He regrets that he told her the news so suddenly.",k:"REGRETS",b:"He",e:"her the news so suddenly.",a:["regrets|telling","regrets having|told"],w:"Regret + -ing for something you did."},
{id:"k80",c:"vpat",s:"Learning to drive is not easy.",k:"DIFFICULT",b:"It is",e:"to drive.",a:["difficult|to learn"],w:"It is difficult + to-infinitive."},
{id:"k81",c:"vpat",s:"The guard made us show our passports.",k:"MADE",b:"We",e:"our passports by the guard.",a:["were made|to show"],w:"The passive of make takes a to-infinitive."},
{id:"k82",c:"vpat",s:"I find getting up early difficult.",k:"USED",b:"I",e:"up early.",a:["am not|used to getting"],w:"Be used to + -ing."},
{id:"k83",c:"vpat",s:"Why do we not go out for dinner tonight?",k:"HOW",b:"",e:"going out for dinner tonight?",a:["how|about"],w:"How about + -ing suggests an idea."},
{id:"k84",c:"vpat",s:"She prefers walking to cycling.",k:"RATHER",b:"She",e:"than cycle.",a:["would rather|walk"],w:"Would rather + bare infinitive + than + bare infinitive."},
{id:"k85",c:"link",s:"Despite the rain, we enjoyed the trip.",k:"ALTHOUGH",b:"We enjoyed the trip",e:".",a:["although it|rained","although it|was raining"],w:"Although + clause. Despite + noun."},
{id:"k86",c:"link",s:"The train was late because of the snow.",k:"DUE",b:"The train was late",e:"the snow.",a:["due|to"],w:"Due to + noun."},
{id:"k87",c:"link",s:"I took a taxi so that I would not miss my flight.",k:"ORDER",b:"I took a taxi",e:"my flight.",a:["in order|not to miss"],w:"In order (not) to + infinitive shows purpose."},
{id:"k88",c:"link",s:"I do not know the man standing by the door.",k:"WHO",b:"I do not know the man",e:"standing by the door.",a:["who|is"],w:"Who is + -ing: a full relative clause."},
{id:"k89",c:"link",s:"She went to work even though she was ill.",k:"DESPITE",b:"She went to work",e:"ill.",a:["despite|being","despite having|been"],w:"Despite + -ing."},
{id:"k90",c:"link",s:"There was a lot of traffic, so we were late.",k:"RESULT",b:"There was a lot of traffic. As",e:", we were late.",a:["a|result"],w:"As a result introduces a consequence."}
]);
