/* Part 1 traps, batch 3 (Cambridge-style, B2-C1). Original sentences. Answers are mine: teacher review advised. UK spelling. Load after part1b.js. */
window.CLOZE=(window.CLOZE||[]).concat([
{id:"v1",p:1,c:"colloc",s:"Unemployment has remained stubbornly ___ in the region.",a:"high",o:["wide","great","large"],w:"Stubbornly high."},
{id:"v2",p:1,c:"vocab",s:"This kind of house is ___ of the period.",a:"typical",o:["common","usual","everyday"],w:"Typical of = a good example of."},
{id:"v3",p:1,c:"colloc",s:"She stared in stunned ___ at the final score.",a:"disbelief",o:["doubt","dispute","uncertainty"],w:"In disbelief."},
{id:"v4",p:1,c:"colloc",s:"She is ___ the best swimmer in the school.",a:"by far",o:["by much","largely","mostly"],w:"By far + superlative."},
{id:"v5",p:1,c:"vocab",s:"Few candidates could ___ the last question.",a:"answer",o:["satisfy","match","serve"],w:"Answer a question. Satisfy a demand."},
{id:"v6",p:1,c:"colloc",s:"The plan looks good on paper, but in ___ it is difficult.",a:"practice",o:["action","operation","work"],w:"In practice = in real life."},
{id:"v7",p:1,c:"vocab",s:"She remained ___ throughout the crisis.",a:"composed",o:["settled","fixed","ordered"],w:"Composed = calm and in control."},
{id:"v8",p:1,c:"link",s:"___ the committee had already decided, there was no point in arguing.",a:"Since",alt:["As"],o:["Out of","So","Owing to"],w:"Since or as = because."},
{id:"v9",p:1,c:"colloc",s:"The ___ limit on this road is thirty miles an hour.",a:"speed",o:["hurry","rush","dash"],w:"Speed limit."},
{id:"v10",p:1,c:"colloc",s:"Their narrow victory was widely seen as well-___.",a:"deserved",o:["fine","right","fair"],w:"A well-deserved victory."},
{id:"v11",p:1,c:"colloc",s:"She is highly ___ by her colleagues.",a:"regarded",o:["thought","believed","judged"],w:"Highly regarded."},
{id:"v12",p:1,c:"vocab",s:"Visitors to the island ___ over fifty thousand last year.",a:"numbered",o:["counted","imagined","considered"],w:"Number = add up to."},
{id:"v13",p:1,c:"vocab",s:"The critic ___ on the quality of the singing.",a:"remarked",o:["noticed","saw","observed"],w:"Remark on = comment on."},
{id:"v14",p:1,c:"colloc",s:"While the manager is away, the deputy is in ___ of the shop.",a:"charge",o:["expense","earning","spending"],w:"In charge of."},
{id:"v15",p:1,c:"colloc",s:"She is very ___ about what she eats.",a:"particular",o:["complete","thorough","detailed"],w:"Particular about = fussy."},
{id:"v16",p:1,c:"colloc",s:"___ speaking, this is not allowed.",a:"Strictly",o:["Strongly","Surely","Slightly"],w:"Strictly speaking."},
{id:"v17",p:1,c:"colloc",s:"Let me give you a piece of ___.",a:"advice",o:["mind","suggestion","statement"],w:"A piece of advice."},
{id:"v18",p:1,c:"colloc",s:"Pregnant women should avoid dishes containing ___ eggs.",a:"raw",o:["plain","natural","normal"],w:"Raw eggs."},
{id:"v19",p:1,c:"colloc",s:"Entry is strictly ___ to ticket holders.",a:"limited",o:["filled","surrounded","planted"],w:"Strictly limited to."},
{id:"v20",p:1,c:"colloc",s:"He is so nervous that he is afraid of his own ___.",a:"shadow",o:["shade","depth","screen"],w:"Afraid of your own shadow."},
{id:"v21",p:1,c:"vocab",s:"The farmers hope to ___ the crop in September.",a:"harvest",o:["transfer","empty","lift"],w:"Harvest a crop."},
{id:"v22",p:1,c:"colloc",s:"They had to ___ lots to decide who went first.",a:"draw",o:["send","turn","pass"],w:"Draw lots."},
{id:"v23",p:1,c:"colloc",s:"The firm has a ___ trained workforce.",a:"highly",o:["widely","entirely","greatly"],w:"Highly trained."},
{id:"v24",p:1,c:"colloc",s:"There has been a ___ improvement in her results.",a:"marked",o:["signed","printed","labelled"],w:"A marked improvement = a clear one."},
{id:"v25",p:1,c:"colloc",s:"Scientists have noted an increase in seismic ___.",a:"activity",o:["process","progress","action"],w:"Seismic activity."},
{id:"v26",p:1,c:"colloc",s:"The novel is ___ in a small Scottish village.",a:"set",o:["placed","handed","put"],w:"A story is set in a place."},
{id:"v27",p:1,c:"vocab",s:"He ___ his fist on the table and left the room.",a:"banged",o:["ground","cracked","broken"],w:"Bang your fist."},
{id:"v28",p:1,c:"colloc",s:"Only the court has the ___ to change the rules.",a:"power",o:["attitude","reason","skill"],w:"Have the power to."},
{id:"v29",p:1,c:"vocab",s:"Dark clouds usually ___ that rain is coming.",a:"indicate",o:["judge","examine","rate"],w:"Indicate = show."},
{id:"v30",p:1,c:"colloc",s:"The patient needs ___ medical attention.",a:"immediate",o:["first","straight","punctual"],w:"Immediate attention."},
{id:"v31",p:1,c:"colloc",s:"The airline refused to ___ any concession.",a:"make",o:["order","prepare","form"],w:"Make a concession."},
{id:"v32",p:1,c:"pv",s:"The trip has been put ___ twice already.",a:"off",o:["out","away","up"],w:"Put off = delay."},
{id:"v33",p:1,c:"colloc",s:"The summit is ___ in Geneva every two years.",a:"held",o:["got","did","kept"],w:"Hold a meeting."},
{id:"v34",p:1,c:"vocab",s:"There is still a huge amount of ___ to be done.",a:"work",o:["job","profession","career"],w:"Work is uncountable. A job is countable."},
{id:"v35",p:1,c:"vocab",s:"The dog ___ that something was wrong.",a:"sensed",o:["experienced","lived","had"],w:"Sense = feel without being told."},
{id:"v36",p:1,c:"link",s:"___ the merger, profits have fallen steadily.",a:"Since",o:["As","While","Because"],w:"Since + a point in time."},
{id:"v37",p:1,c:"vocab",s:"At the station she suddenly ___ that her passport was missing.",a:"noticed",o:["glanced","looked","watched"],w:"Notice that."},
{id:"v38",p:1,c:"vocab",s:"After one year she was ___ to manager.",a:"promoted",o:["advertised","publicised","announced"],w:"Promoted to."},
{id:"v39",p:1,c:"vocab",s:"The committee ___ of six independent experts.",a:"consists",o:["deals","involves","composes"],w:"Consist of. Composed of needs was."},
{id:"v40",p:1,c:"colloc",s:"Anyone with information should make ___ with the police.",a:"contact",o:["touch","general","common"],w:"Make contact with."},
{id:"v41",p:1,c:"vocab",s:"The airline has a ___ of forty aircraft.",a:"fleet",o:["staff","crew","set"],w:"A fleet of ships or planes."},
{id:"v42",p:1,c:"colloc",s:"Despite many ___ of help, he refused them all.",a:"offers",o:["requests","replies","questions"],w:"An offer of help."},
{id:"v43",p:1,c:"vocab",s:"Engineers ___ the cost at about twenty thousand pounds.",a:"estimated",o:["balanced","numbered","counted"],w:"Estimate = guess roughly."},
{id:"v44",p:1,c:"vocab",s:"I am ___ to your letter of 5 May.",a:"referring",o:["seeking","working","expecting"],w:"Referring to = writing about."},
{id:"v45",p:1,c:"vocab",s:"The new stadium has ___ all our expectations.",a:"fulfilled",o:["occupied","possessed","covered"],w:"Fulfil expectations."},
{id:"v46",p:1,c:"colloc",s:"Passengers must go on ___ by six o'clock.",a:"board",o:["plane","flight","air"],w:"Go on board."},
{id:"v47",p:1,c:"colloc",s:"The animals had no ___ from the harsh winter.",a:"shelter",o:["guard","care","help"],w:"Shelter from the weather."},
{id:"v48",p:1,c:"colloc",s:"It is hardly ___ that the hardest workers get the least.",a:"fair",o:["enough","plenty","adequate"],w:"Hardly fair = not fair."}
]);
