"""Speaking Part 2 — build part2-turn.json (v3).

Content words are written inside [[double brackets]]. The build removes the
brackets for the spoken text and turns each one into ___ for the pattern, so
the pattern can never drift from the answer.

Long turn: 50–60 s. Partner question: 20–30 s. Both at 2.5 words a second.
"""
import json, re, sys

def S(m, t, marks=(), wrong=()):
    s = {"m": m, "t": t}
    if marks: s["marks"] = list(marks)
    if wrong: s["wrong"] = [{"t": a, "why": b} for a, b in wrong]
    return s
def T(why, *segs): return {"why": why, "segs": list(segs)}

# ── why a wrong option is wrong ──
DESCRIBE = "Pure description. The examiner can see the photo — say what you think is going on, and why."
PREF     = "That's your own preference. Save it for the partner's question — the minute is about the people in the photos."
NOCOMP   = "This talks about one photo on its own. Link it to the other: 'on the other hand', 'whereas', 'by contrast'."
TOOSURE  = "Too certain. You can't know from a photo — 'might', 'probably', 'I imagine' keep it honest."
ENDING   = "A stock ending that says nothing. Sum up with one idea that joins both photos."
OFFQ     = "It forgets the printed question. Every part of the minute should answer it."
LONGCMP  = "A second round of comparing. One sentence is enough — then answer the question."
FORMAL   = "Correct English, but it sounds like an essay. Speak like yourself."
STOCK    = "The examiner hears this fifty times a day. React to the question instead."
FLAT     = "Flat. Show how you feel about the question."
SAME     = "That's the answer again. This move has to add something new."
VAGUE    = "Vague. An example is one moment you could film — a day, a place, a person."
NOTURN   = "No turn. A contrast has to swing back the other way."
GEN      = "About people in general, not about you."

TASKS = []
def task(id_, tab, q, fu, p1, p2, alts):
    TASKS.append({"id": id_, "tab": tab, "question": q, "followUp": fu,
                  "photos": [{"title": p1[0], "brief": p1[1]}, {"title": p2[0], "brief": p2[1]}],
                  "alts": alts})

# ═════════════════════════════ 1 · STUDY
task("study", "Study",
 "Compare the photographs and say why the people have chosen to study in these places.",
 "Where do you prefer to study?",
 ("Library", "A teenage girl studying alone in a quiet library, surrounded by books."),
 ("Café", "A teenage boy studying at a café table in the old town, with a laptop and a hot drink."),
 [ {"turn": T("One sentence of comparing, then each photo answers the question. The ending joins them with one idea: it depends on the pressure.",
     S("k", "Both photos show people studying, but they've chosen really different places to do it.", ["Both photos show", "but they've chosen"]),
     S("p", "The girl in the first photo is in a [[library]], and I imagine she's chosen it because it's [[completely silent]]. She looks very focused, so maybe she's got [[an important exam coming up]] and she can't afford any distractions — [[no phone, no friends, nothing]].",
       ["I imagine she's chosen it because", "She looks very focused, so maybe", "she can't afford any distractions"],
       wrong=[("In the first photo there is a girl, a table and a lot of books on the shelves.", DESCRIBE),
              ("I prefer libraries because I need silence to concentrate.", PREF)]),
     S("q", "The boy in the café, on the other hand, seems much more relaxed. He's probably the kind of person who finds [[total silence]] a bit stressful, so [[the background noise and a hot chocolate]] might actually help him concentrate. Or perhaps he just needs [[a change of scene]] after studying at home all week.",
       ["on the other hand", "He's probably the kind of person who", "might actually help him", "Or perhaps he just needs"],
       wrong=[("The boy is in a café. He has a laptop and a drink, and he is wearing a jumper.", NOCOMP),
              ("The boy is definitely studying for the same exam as the girl.", TOOSURE)]),
     S("s", "So I'd say it really depends on the person — and on how much pressure they're under.",
       ["So I'd say it really depends on"],
       wrong=[("In conclusion, both photos are very interesting.", ENDING),
              ("Both photos also show tables and chairs.", LONGCMP)])),
    "partner": T("A clear preference, then an honest problem with it. Thirty seconds is enough for that.",
     S("x", "Oh, definitely at [[home]], in my own bedroom.", ["Oh, definitely"],
       wrong=[("I study at home.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "I need my own [[desk]], and I like having all my things around me, like my music.", ["I like having"]),
     S("c", "The only problem is that my [[phone]]'s always there too, so I have to put it in another room, or I'd never get anything done.",
       ["The only problem is that", "or I'd never get anything done"],
       wrong=[("And my bedroom is quite big.", NOTURN), ("However, many students prefer libraries.", GEN)]))},
   {"turn": T("The contrast here is about people, not places: one wants to shut the world out, the other wants to feel part of it.",
     S("k", "What these photos have in common is that both people are studying, but the atmosphere couldn't be more different.", ["What these photos have in common is that", "couldn't be more different"]),
     S("p", "In the library, it's all about [[silence and routine]]. The girl has probably come straight after school, because she knows that at home [[there'd be too many interruptions]] — [[little brothers, the TV, her mum asking her to help]].",
       ["it's all about", "has probably come", "because she knows that"],
       wrong=[("The library has very tall shelves and a big window.", DESCRIBE),
              ("The girl hates her family, so she never studies at home.", TOOSURE)]),
     S("q", "Whereas the boy in the café looks like he's chosen it for [[the company]] as much as for studying. Maybe he's waiting for [[his friends]], or he just likes [[being around people]], even if he's working on his own. I don't think he's under as much pressure as she is — he looks like he could stop any minute for [[a chat]].",
       ["Whereas", "as much as", "Maybe he's waiting for", "I don't think he's under as much pressure as"],
       wrong=[("The café has nice cakes and the coffee looks good.", OFFQ),
              ("I would choose the café because I like coffee.", PREF)]),
     S("s", "So one of them wants to shut the world out, and the other one wants to feel part of it.",
       ["So one of them", "and the other one"],
       wrong=[("That's all I can say about the photos.", ENDING),
              ("Both of them are also wearing casual clothes.", LONGCMP)])),
    "partner": T("A surprising choice needs a reason fast. The 'mind you' shows you've thought about when it doesn't work.",
     S("a", "In a [[café]], honestly, especially the ones in the [[old town]].", ["honestly, especially"]),
     S("r", "If I'm at home, I end up on my [[phone]], but in a café I feel a bit embarrassed not to be working, so I actually concentrate.",
       ["I end up on", "I feel a bit embarrassed", "so I actually concentrate"],
       wrong=[("I prefer cafés because I like cafés.", "Circular — why?"), ("Cafés are popular with students.", GEN)]),
     S("c", "Mind you, it's not great right before [[exams]], when I need total silence.", ["Mind you", "right before"],
       wrong=[("And the cakes are good.", NOTURN), ("However, cafés can be expensive.", GEN)]))},
   {"turn": T("Speculating about situations, not just places: one of them might have no quiet space at home. That's thinking, not describing.",
     S("k", "In both photos someone's studying, but I get the feeling they're in very different situations.", ["I get the feeling"]),
     S("p", "The girl in the library looks quite [[serious and a bit tired]], to be honest. I imagine she's chosen the library because it's [[free, quiet and open late]], and she might have [[a big test tomorrow]]. It could even be that she doesn't have [[a quiet place to study at home]].",
       ["looks quite", "to be honest", "she might have", "It could even be that"],
       wrong=[("The girl has long hair and she is reading a book.", DESCRIBE),
              ("She has a test tomorrow and she is going to fail it.", TOOSURE)]),
     S("q", "The boy in the café, by contrast, seems to be taking it easy. It's quite likely he's doing something [[less stressful, like reading or a project]], so he doesn't mind [[the noise]]. And to be fair, if you're in [[the old town]], it's a lovely place to spend an afternoon.",
       ["by contrast", "seems to be taking it easy", "It's quite likely", "to be fair"],
       wrong=[("The boy is also studying, like the girl.", LONGCMP),
              ("In the café there are other people and a waiter.", NOCOMP)]),
     S("s", "So for her it's probably about necessity, and for him it's more about enjoying himself.",
       ["it's probably about", "it's more about"],
       wrong=[("Anyway, I like both photos.", ENDING), ("I think studying is very important for young people.", OFFQ)])),
    "partner": T("'It depends' — then both sides, and one small moment to prove the second.",
     S("x", "It depends what I'm studying.", ["It depends what"],
       wrong=[("I study in many places.", "Vague, and not a reaction."), ("Well, that's a good question.", STOCK)]),
     S("a", "For [[Maths]] I need complete silence, so I go to the [[library near my school]].", ["I need complete silence"]),
     S("c", "But for things like [[History or English]], I'm perfectly happy at the [[kitchen table]], even with my whole family chatting around me.",
       ["I'm perfectly happy", "even with"],
       wrong=[("And the library is very quiet.", NOTURN), ("However, silence helps most people.", GEN)]),
     S("e", "Last week I learnt a whole list of [[dates]] while my mum was cooking dinner.", ["Last week", "while my mum was"],
       wrong=[("For example, I study a lot.", VAGUE), ("History has many dates.", "A fact, not a moment.")]))} ])

# ═════════════════════════════ 2 · SPORT
task("sport", "Sport",
 "Compare the photographs and say what the people might enjoy about doing exercise in these ways.",
 "Would you rather exercise alone or with other people?",
 ("Gym", "A young man working out alone in a modern gym in Funchal, with headphones on."),
 ("Levada walk", "A group of teenagers and adults walking a levada path through a green forest."),
 [ {"turn": T("Each photo gets its own kind of enjoyment: control on one side, company on the other. The ending names the difference.",
     S("k", "Both photos show people keeping fit, but in completely different ways.", ["Both photos show", "in completely different ways"]),
     S("p", "The man in the gym is on his own with [[his headphones on]], so I think what he enjoys is [[the control]]. He can decide [[exactly how hard he trains]], it doesn't matter [[if it's raining]], and nobody's waiting for him. He might be training for [[something specific, like a race]].",
       ["so I think what he enjoys is", "He can decide", "nobody's waiting for him", "He might be training for"],
       wrong=[("In the first photo there's a man, some machines and a big mirror.", DESCRIBE),
              ("I don't like gyms because they're boring.", PREF)]),
     S("q", "The group on the levada, on the other hand, are probably enjoying [[the company]] as much as the exercise. They look like they're [[chatting and taking their time]], and with [[all that green forest around them]], it hardly feels like exercise at all. I bet they stop for photos every five minutes.",
       ["on the other hand", "are probably enjoying", "as much as", "it hardly feels like"],
       wrong=[("The group is walking on a levada in the forest.", NOCOMP),
              ("They are definitely a family from Santana.", TOOSURE)]),
     S("s", "So I suppose one is about the body, and the other is more about the mind — and having fun together.",
       ["So I suppose one is about", "the other is more about"],
       wrong=[("In conclusion, sport is good for you.", ENDING), ("Both photos also show people wearing trainers.", LONGCMP)])),
    "partner": T("React, answer, give the reason from experience — and one real Saturday as proof.",
     S("x", "Oh, with other people, definitely!", ["definitely"],
       wrong=[("With other people.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "I'm so much more motivated when I'm with my [[friends]].", ["I'm so much more motivated when"]),
     S("r", "On my own, I get bored after about [[ten minutes]] and start making excuses to stop.", ["start making excuses"],
       wrong=[("I prefer it because I like it.", "Circular."), ("Exercising with others is healthier.", GEN)]),
     S("e", "Last Saturday, for example, we walked for [[three hours]] on a [[levada]] and hardly noticed the time, even though it was raining.", ["Last Saturday", "hardly noticed the time"],
       wrong=[("For example, I go with my friends.", SAME), ("Levadas are very long.", "A fact, not a moment.")]))},
   {"turn": T("'The similarities pretty much end there' is a confident way to stop comparing. Then goals versus journey.",
     S("k", "The thing both photos have in common is exercise — but the similarities pretty much end there.", ["The thing both photos have in common is", "the similarities pretty much end there"]),
     S("p", "In the gym, the man looks really determined. I imagine he enjoys [[pushing himself]] and [[seeing his progress]] — maybe he writes down [[how much he lifts every week]]. It's quite a private kind of exercise, so perhaps he likes having [[time to think, or to switch off completely]].",
       ["looks really determined", "I imagine he enjoys", "so perhaps he likes"],
       wrong=[("He is lifting weights and he is wearing a grey T-shirt.", DESCRIBE),
              ("He is a professional bodybuilder.", TOOSURE)]),
     S("q", "Whereas the people on the levada seem much more relaxed about it. What they probably enjoy most is [[being outdoors]] — [[the fresh air]], [[the waterfalls]], maybe stopping for [[a picnic]] halfway. And because it's a group, there's always someone to [[encourage you when you're tired]].",
       ["Whereas", "What they probably enjoy most is", "there's always someone to"],
       wrong=[("I love levadas — I walk them every weekend.", PREF), ("There are trees and a path in the second photo.", NOCOMP)]),
     S("s", "So I'd say the gym is for people who like goals, and the levada is for people who like the journey.",
       ["So I'd say", "is for people who like"],
       wrong=[("Those are my ideas about the photos.", ENDING), ("Both activities are also quite cheap.", OFFQ)])),
    "partner": T("A less popular answer, defended with a real habit — then a fair exception.",
     S("x", "Alone, to be honest.", ["to be honest"],
       wrong=[("I don't know.", "A closed door."), ("Well, that's a good question.", STOCK)]),
     S("a", "I go running along the [[seafront]] early in the morning, before anyone's up.", ["before anyone's up"]),
     S("r", "It's the only time of day when nobody's talking to me, and I can just listen to [[music]] and think.", ["It's the only time of day when"],
       wrong=[("I run alone because I'm alone.", "Circular."), ("Running is good exercise.", GEN)]),
     S("c", "Although if I'm training for a [[race]], it helps to have a friend to push me.", ["Although if I'm", "it helps to have"],
       wrong=[("And the seafront is beautiful.", NOTURN), ("However, running alone can be dangerous.", GEN)]))},
   {"turn": T("Fitting exercise into life versus making a day of it — a nice idea that includes locals and tourists.",
     S("k", "Both pictures show people exercising, but I think they'd enjoy very different things about it.", ["I think they'd enjoy"]),
     S("p", "The man in the gym probably likes that it's [[efficient]]. He can go [[straight after work]], do [[an hour]], and go home. He might also enjoy [[the music]] and [[the feeling of being strong]] — some people find that really satisfying.",
       ["probably likes that it's", "He might also enjoy", "some people find that really satisfying"],
       wrong=[("The gym is very modern and clean.", OFFQ), ("He enjoys lifting weights because he is strong.", "Circular — and it doesn't compare.")]),
     S("q", "The group on the levada, though, look like they're enjoying [[the scenery]] more than anything. I'd guess some of them are [[tourists]], and for them it's [[an adventure]]. And for the locals it might be [[a family tradition]] — lots of families here walk the levadas on Sundays.",
       ["though", "more than anything", "I'd guess", "it might be"],
       wrong=[("The people in the second photo are also exercising.", LONGCMP), ("They are all tourists from Germany.", TOOSURE)]),
     S("s", "So in a way, one is about fitting exercise into a busy life, and the other is making a day out of it.",
       ["So in a way", "making a day out of it"],
       wrong=[("I hope that answers the question.", ENDING), ("I'd rather go on the levada.", PREF)])),
    "partner": T("A funny condition in the answer, and a story that explains it.",
     S("a", "With other people, but only people who walk at [[my speed]]!", ["but only"]),
     S("e", "Last month I went with my [[cousin]], who's really sporty, and I spent the whole walk trying to catch up.", ["Last month", "I spent the whole walk"],
       wrong=[("For example, I walk with people.", VAGUE), ("My cousin likes sport.", "A fact, not a moment.")]),
     S("c", "So now I go with my [[best friend]] — we're both slow, and we both stop for photos of the waterfalls.", ["So now I go with", "we're both"],
       wrong=[("And my cousin is very fast.", NOTURN), ("However, walking alone is relaxing.", GEN)]))} ])

# ═════════════════════════════ 3 · HOLIDAYS
task("holidays", "Holidays",
 "Compare the photographs and say why the people might have chosen to spend their holiday in these places.",
 "Which of these places would you rather visit?",
 ("Porto Moniz", "A family swimming in the natural volcanic pools at Porto Moniz, with waves breaking on the rocks."),
 ("Cabo Girão", "Two young hikers at the Cabo Girão viewpoint, looking down from a very high cliff."),
 [ {"turn": T("Safe and relaxing versus adrenaline. The ending says what each group wants from the day.",
     S("k", "Both photos show people on holiday in Madeira, but they're looking for really different experiences.", ["Both photos show", "they're looking for"]),
     S("p", "The family at Porto Moniz have probably chosen it because it's [[safe and relaxing]]. The natural pools are [[protected from the waves]], so the parents can [[sit back]] while the children swim. It might also be [[the kind of place they come back to every summer]]. Their grandparents might even be with them.",
       ["have probably chosen it because", "so the parents can", "It might also be"],
       wrong=[("In the first photo there are pools, rocks and some people swimming.", DESCRIBE),
              ("I love Porto Moniz — I go every year.", PREF)]),
     S("q", "The two hikers at Cabo Girão, on the other hand, seem to be after [[a bit more excitement]]. I imagine they're [[young tourists]] who want [[amazing photos]] and [[a bit of adrenaline]] — standing on the edge of a cliff that high is definitely not relaxing!",
       ["on the other hand", "seem to be after", "I imagine they're"],
       wrong=[("Cabo Girão is one of the highest cliffs in Europe.", "A guidebook fact. Why did THESE people choose it?"),
              ("The hikers are definitely scared.", TOOSURE)]),
     S("s", "So I suppose the family want to switch off, while the hikers want something to remember.",
       ["So I suppose", "while"],
       wrong=[("In conclusion, Madeira is a beautiful island.", ENDING), ("Both places are also on the coast.", LONGCMP)])),
    "partner": T("The less obvious choice, explained — and a funny weakness at the end.",
     S("x", "Ooh, [[Cabo Girão]], I think.", ["Ooh", "I think"],
       wrong=[("Cabo Girão.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "I've been to [[Porto Moniz]] loads of times with my family, so it doesn't feel like an adventure any more, even though I love it.",
       ["loads of times", "it doesn't feel like", "even though"]),
     S("c", "Although to be honest, I'm a bit scared of [[heights]], so I'd probably stay well away from the edge!", ["Although to be honest", "stay well away from"],
       wrong=[("And the view is amazing.", NOTURN), ("However, cliffs can be dangerous for tourists.", GEN)]))},
   {"turn": T("Slowing down in one place versus seeing as much as possible — an idea about travel, not just two places.",
     S("k", "What both photos have in common is that people are enjoying Madeira's landscape, although in very different ways.", ["What both photos have in common is that", "although in very different ways"]),
     S("p", "In the first one, the family look like they want [[a proper beach day]] — [[swimming, sunbathing, maybe lunch in a café nearby]]. Porto Moniz is [[a bit far from Funchal]], so they've probably planned it as [[a special day out]], maybe for someone's birthday.",
       ["look like they want", "so they've probably planned it as"],
       wrong=[("The water is blue and there are some rocks.", DESCRIBE), ("Porto Moniz is in the north-west of the island.", OFFQ)]),
     S("q", "The hikers, by contrast, have chosen a place where the point is [[the view]], not [[the water]]. They might be [[doing a tour of the island]] and ticking off [[the famous viewpoints]]. I'd guess they're not staying long — they'll take their photos and move on.",
       ["by contrast", "where the point is", "They might be", "I'd guess"],
       wrong=[("I'd rather go to Cabo Girão because I like views.", PREF), ("The hikers have backpacks and hats.", NOCOMP)]),
     S("s", "So one holiday is about slowing down in one place, and the other is about seeing as much as possible.",
       ["So one holiday is about", "and the other is about"],
       wrong=[("That's what I think about the photos.", ENDING), ("Both groups are also wearing summer clothes.", LONGCMP)])),
    "partner": T("A firm answer, a reason with detail, and a memory that proves it.",
     S("x", "Oh, [[Porto Moniz]], no question.", ["no question"],
       wrong=[("Porto Moniz, maybe.", "Too weak for how sure the rest is."), ("Well, that's a good question.", STOCK)]),
     S("a", "I love [[swimming]], and those pools are amazing — you're in the Atlantic, but you're protected from the big waves.", ["you're in", "but you're protected from"]),
     S("e", "Last summer I spent a whole afternoon there with my [[cousins]], jumping in and out of the pools, and we didn't want to leave when it got dark.", ["Last summer", "we didn't want to leave"],
       wrong=[("For example, the pools are big.", VAGUE), ("The pools were made by lava.", "A fact, not a moment.")]))},
   {"turn": T("Comfort versus experience. The speculation about young children and a coastal walk shows real thinking.",
     S("k", "Both pictures show people on holiday on the island, but I think they had different reasons for choosing these places.", ["I think they had different reasons for"]),
     S("p", "The family in Porto Moniz might have [[young children]], so they've chosen somewhere [[easy]] — the pools are [[calm]], there are [[showers and cafés]], and nobody has to walk very far. It's probably [[the kind of holiday where the parents actually get to rest]].",
       ["might have", "so they've chosen somewhere", "It's probably the kind of"],
       wrong=[("There is a family in the water and a mother on the rocks.", DESCRIBE), ("They definitely come from Lisbon.", TOOSURE)]),
     S("q", "The hikers at Cabo Girão seem to be the adventurous type. I'd imagine they chose it because it's [[one of the highest cliffs in Europe]], and they wanted to [[see it for themselves]]. They might even be walking [[the whole coast]], so this is just [[one stop]].",
       ["seem to be the adventurous type", "I'd imagine they chose it because", "They might even be"],
       wrong=[("The hikers are also on holiday, like the family.", LONGCMP), ("I'd love to go there with my friends.", PREF)]),
     S("s", "So the family are thinking about comfort, whereas the hikers are thinking about the experience.",
       ["are thinking about", "whereas"],
       wrong=[("I think both holidays are nice.", ENDING), ("Holidays are important for everyone.", OFFQ)])),
    "partner": T("Refusing to choose can work, if you turn it into a plan.",
     S("x", "Honestly? I'd want to do both in the same day!", ["Honestly?", "I'd want to"],
       wrong=[("Both.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "We could see the view at [[Cabo Girão]] in the morning, and then drive to [[Porto Moniz]] for a swim.", ["We could", "and then"]),
     S("c", "My [[dad]] would say it's too much driving, but I think it would be the perfect day out with my friends.", ["would say", "but I think it would be"],
       wrong=[("And both places are beautiful.", NOTURN), ("However, driving in Madeira is difficult.", GEN)]))} ])

# ═════════════════════════════ 4 · FOOD
task("food", "Food",
 "Compare the photographs and say how the people might be feeling.",
 "Do you prefer eating at home or eating out?",
 ("Family kitchen", "A family cooking and eating together in a small, busy kitchen at home."),
 ("Zona Velha restaurant", "A group of friends eating espetada at a lively restaurant in the old town."),
 [ {"turn": T("Feelings, not food: relaxed and cosy versus excited and special. The bill joke makes it human.",
     S("k", "Both photos show people sharing a meal, but the atmosphere in each one is quite different.", ["Both photos show", "the atmosphere in each one"]),
     S("p", "The family at home look [[really relaxed]]. I imagine they're feeling [[comfortable]], because they can [[talk about anything]] and nobody's in a hurry. The kitchen's a bit small and [[crowded]], but that probably makes it feel [[even cosier]]. It might be a Sunday, when everyone's at home.",
       ["look", "I imagine they're feeling", "nobody's in a hurry", "but that probably makes it feel"],
       wrong=[("The family are eating soup and there is bread on the table.", DESCRIBE), ("I love eating with my family.", PREF)]),
     S("q", "The friends in the restaurant, on the other hand, seem [[excited]] — it might be [[a birthday]] or [[the end of exams]]. They're probably feeling a bit [[more special]], because someone else is cooking and there's [[music and lots of people around]]. Although they might also be a bit worried about [[the bill]]!",
       ["on the other hand", "it might be", "They're probably feeling", "they might also be a bit worried about"],
       wrong=[("They are eating espetada, which is a typical Madeiran dish.", "A food fact — the question asks how they feel."),
              ("They are all very happy because it's a birthday.", TOOSURE)]),
     S("s", "So I'd say the family feel safe and happy, while the friends feel like they're celebrating.",
       ["So I'd say", "while", "feel like"],
       wrong=[("In conclusion, food is very important.", ENDING), ("Both groups are also sitting at tables.", LONGCMP)])),
    "partner": T("An everyday answer with a warm reason, and a special exception.",
     S("x", "Oh, that's a tough one.", ["that's a tough one"],
       wrong=[("I eat at home.", FLAT), ("Well, that's a good question.", STOCK)]),
     S("a", "At [[home]], most of the time.", ["most of the time"]),
     S("r", "My [[mum]]'s a brilliant cook, and it's the only time of day when the whole family's together and nobody's looking at a phone.", ["it's the only time of day when"],
       wrong=[("I prefer home because it's my home.", "Circular."), ("Home cooking is healthier.", GEN)]),
     S("c", "But on special occasions, I love going out for [[espetada]] in the old town — it just feels different.", ["But on special occasions", "it just feels different"],
       wrong=[("And my mum's food is delicious.", NOTURN), ("However, restaurants are expensive.", GEN)]))},
   {"turn": T("Everyday moment versus occasion. 'Relaxed' against 'buzzing' — two strong feeling words.",
     S("k", "In both pictures people are eating together, although one feels like an everyday moment and the other like an occasion.", ["although one feels like", "and the other like"]),
     S("p", "The family at home look like they're feeling [[close and comfortable]]. Maybe it's [[a Sunday]], and everyone's [[helping with the cooking]] — that's the kind of thing that makes people feel [[part of a team]]. I'd guess there's [[a lot of laughing and a bit of arguing]], like in my house.",
       ["look like they're feeling", "that's the kind of thing that makes people feel", "I'd guess there's"],
       wrong=[("There are five people in the kitchen and the table is small.", DESCRIBE), ("They are definitely arguing about money.", TOOSURE)]),
     S("q", "The group in the Zona Velha restaurant seem [[more energetic]]. They're probably feeling [[excited to be out]], and maybe a bit [[show-offy]] — taking photos of the food, ordering [[something they've never tried]]. It looks noisy, but in a good way.",
       ["seem", "They're probably feeling", "and maybe a bit", "It looks noisy, but in a good way"],
       wrong=[("I'd love to eat there with my friends.", PREF), ("The restaurant has red tablecloths.", NOCOMP)]),
     S("s", "So the family are relaxed and at home, whereas the friends are buzzing with excitement.", ["whereas", "are buzzing"],
       wrong=[("Those are my ideas.", ENDING), ("Eating together is good for families.", OFFQ)])),
    "partner": T("An honest answer with a money problem — very fourteen — and a small grown-up feeling.",
     S("x", "Out, definitely — but I can't afford it very often!", ["but I can't afford it very often"],
       wrong=[("Out.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "When I do, I go with my friends to a little place near the [[market]] that does really cheap [[bolo do caco]] with garlic butter.", ["When I do", "a little place near"]),
     S("r", "It feels grown-up, eating out without your [[parents]], even if it's only a sandwich and a drink.", ["It feels grown-up", "even if it's only"],
       wrong=[("I like it because the food is good.", "Thin. What does it feel like?"), ("Eating out is popular with teenagers.", GEN)]))},
   {"turn": T("Two kinds of happiness, quiet and loud. Speculating about someone coming home adds a story.",
     S("k", "Both photos show people enjoying food with others, but I think the feelings behind them are different.", ["the feelings behind them"]),
     S("p", "The family in the kitchen probably feel [[very at ease]]. They don't have to [[dress up]] or [[behave perfectly]] — they can just be themselves. It's also possible that [[someone has just come home]], and this meal is [[a way of welcoming them]].",
       ["probably feel", "They don't have to", "they can just be themselves", "It's also possible that"],
       wrong=[("The kitchen is small and there are many plates.", DESCRIBE), ("I also eat in the kitchen with my family.", PREF)]),
     S("q", "The friends in the restaurant, by contrast, might be feeling [[a mix of excitement and nerves]], especially if it's [[their first time out together]]. Restaurants like that in the old town are [[busy and quite loud]], so they're probably [[having to shout]] a bit, but they seem to be loving it.",
       ["by contrast", "might be feeling", "especially if", "they seem to be loving it"],
       wrong=[("The friends are also eating food, like the family.", LONGCMP), ("They are nervous because the food is bad.", TOOSURE)]),
     S("s", "So one is a quiet kind of happiness, and the other is a louder, more exciting kind.",
       ["So one is a", "kind of", "and the other is"],
       wrong=[("Anyway, both photos show food.", ENDING), ("I think restaurants are too expensive.", PREF)])),
    "partner": T("A modest answer, a reason, then a grandma who breaks the rule — with one real meal.",
     S("x", "Hmm, honestly?", ["honestly?"],
       wrong=[("Home.", FLAT), ("Well, that's a good question.", STOCK)]),
     S("a", "Definitely at [[home]]. I'm quite a fussy eater, so at home I know I'll like everything.", ["I'm quite a fussy eater"]),
     S("c", "Mind you, my [[grandma]]'s cooking is the exception — I'd eat anything she makes, even [[fish]]!", ["Mind you", "is the exception", "I'd eat anything"],
       wrong=[("And my mum cooks well.", NOTURN), ("However, fussy eating is common in children.", GEN)]),
     S("e", "Last week she made [[tuna steak with milho frito]], and I had three plates, which my mum still talks about.", ["Last week", "I had three plates"],
       wrong=[("For example, she cooks a lot.", VAGUE), ("Milho frito is fried cornmeal.", "A definition, not a moment.")]))} ])

# ═════════════════════════════ 5 · TRANSPORT
task("transport", "Transport",
 "Compare the photographs and say what might be difficult about travelling in these ways.",
 "How do you usually get around?",
 ("City bus", "A crowded yellow city bus in Funchal, with teenagers standing and holding on."),
 ("Mountain road", "A man driving alone on a narrow, winding mountain road in the fog."),
 [ {"turn": T("Comfort versus stress. Each photo gets two difficulties, both speculated, not seen.",
     S("k", "Both photos show people travelling, but the difficulties they face are probably very different.", ["Both photos show", "the difficulties they face"]),
     S("p", "The people on the bus look [[really squashed]]. The hardest thing for them is probably [[standing for the whole journey]], especially if the bus is [[going up steep hills]]. And if it's [[late]], they might [[miss the start of school]]. It probably doesn't help that everyone's carrying heavy school bags.",
       ["The hardest thing for them is probably", "especially if", "they might"],
       wrong=[("The bus is yellow and there are lots of people inside.", DESCRIBE), ("I take the bus every day.", PREF)]),
     S("q", "The man in the car, on the other hand, has [[a seat and some space]], but the road looks [[narrow and winding]]. I imagine he has to [[concentrate all the time]], because there could be [[a bus coming round the corner]]. And if it's [[foggy]] up there, it must be quite scary.",
       ["on the other hand", "I imagine he has to", "there could be", "it must be quite"],
       wrong=[("The man is driving a white car.", NOCOMP), ("He is definitely lost.", TOOSURE)]),
     S("s", "So on the bus the problem is comfort, but in the car it's more about stress.",
       ["the problem is", "it's more about"],
       wrong=[("In conclusion, transport is important.", ENDING), ("Both are also on roads.", LONGCMP)])),
    "partner": T("The habit, the reason and the honest downside. Useful frames all the way through.",
     S("a", "I usually take the [[bus]] to school, like most of my friends.", ["I usually take"]),
     S("r", "It's cheaper than asking my [[parents]] for lifts all the time, and I can chat to my friends on the way.", ["It's cheaper than", "on the way"],
       wrong=[("I take the bus because I go by bus.", "Circular."), ("Buses are better for the environment.", GEN)]),
     S("c", "The only problem is that in the morning it's so packed that I usually have to stand.", ["The only problem is that", "so packed that"],
       wrong=[("And the drivers are friendly.", NOTURN), ("However, cars are faster.", GEN)]))},
   {"turn": T("Too crowded versus too lonely. The 'no signal' detail is precise speculation.",
     S("k", "What both photos have in common is that neither journey looks very easy.", ["What both photos have in common is that", "neither journey"]),
     S("p", "On the bus, the passengers seem [[tired and a bit fed up]]. I'd imagine the difficult part is [[the crowds]] — you can't [[sit down]], you can't [[move]], and you're [[standing next to strangers]] for half an hour. It might also be [[boiling]] in summer.",
       ["seem", "I'd imagine the difficult part is", "It might also be"],
       wrong=[("There is a girl with a backpack and a man reading.", DESCRIBE), ("The passengers are angry with the driver.", TOOSURE)]),
     S("q", "Whereas the driver in the mountains has the opposite problem — he's [[completely alone]]. The road looks [[really dangerous]], with [[sharp bends and a big drop]] on one side, so he can't [[relax for a second]]. If his car broke down up there, he'd probably have [[no signal]] either, which is quite a scary thought.",
       ["Whereas", "has the opposite problem", "If his car broke down", "he'd probably have"],
       wrong=[("I'd hate to drive there — it's too scary.", PREF), ("The road is grey and there are trees.", NOCOMP)]),
     S("s", "So one journey is too crowded, and the other is maybe a bit too lonely.",
       ["So one journey is", "and the other is maybe"],
       wrong=[("That's everything about the photos.", ENDING), ("Madeira has many roads.", OFFQ)])),
    "partner": T("A habit with a reason built in, and a summer exception that ends with a joke.",
     S("x", "Mostly by [[car]], to be honest.", ["Mostly", "to be honest"],
       wrong=[("Car.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "My [[dad]] drives me to school on his way to work, because the bus doesn't go near our house.", ["on his way to work"]),
     S("c", "Although in summer I cycle along the [[seafront]], which is much more fun, especially early in the morning — as long as it isn't uphill!", ["Although in summer", "as long as"],
       wrong=[("And my dad drives well.", NOTURN), ("However, cycling is dangerous in cities.", GEN)]))},
   {"turn": T("Slow versus stressed — a neat summary. The hire-car idea shows you're thinking about who these people are.",
     S("k", "Both pictures show everyday travel on the island, but each one has its own problems.", ["each one has its own"]),
     S("p", "For the people on the bus, I think the biggest difficulty is [[time]]. Buses here can be [[slow]], and with [[all those stops]], a short journey can take [[forever]]. The teenagers might be [[worried about being late]] — they don't look very happy. And in the rain, the windows steam up and everyone's clothes are wet.",
       ["I think the biggest difficulty is", "can take", "might be"],
       wrong=[("The bus has big windows and red seats.", DESCRIBE), ("The bus is definitely late.", TOOSURE)]),
     S("q", "The man in the car probably gets there [[faster]], but it's not easy either. Mountain roads in Madeira are [[famous for being steep]], so he might [[feel nervous]], especially if he's [[not used to them]]. He could even be [[a tourist in a hire car]], which would be even scarier!",
       ["probably gets there", "but it's not easy either", "He could even be", "which would be even"],
       wrong=[("The car is also travelling, like the bus.", LONGCMP), ("I prefer cars because they're faster.", PREF)]),
     S("s", "So it's a choice between being slow and being stressed.", ["So it's a choice between"],
       wrong=[("I hope that's enough.", ENDING), ("Public transport should be free.", OFFQ)])),
    "partner": T("A simple answer, a reason, a funny downside — and one real walk to prove it.",
     S("a", "I walk almost everywhere, actually.", ["almost everywhere, actually"]),
     S("r", "I live in the [[centre]], so most places are only [[ten minutes]] away.", ["so most places are only"],
       wrong=[("I walk because I like walking.", "Circular."), ("Walking is healthy.", GEN)]),
     S("c", "My legs are always tired, though — [[Funchal]] is basically one big hill!", ["though", "is basically"],
       wrong=[("And I like the fresh air.", NOTURN), ("However, walking is slow.", GEN)]),
     S("e", "Yesterday I walked from my house to the [[Lido]] and back, and I felt like I'd climbed a mountain.", ["Yesterday", "I felt like I'd"],
       wrong=[("For example, I walk a lot.", VAGUE), ("The Lido is a swimming pool.", "A fact, not a moment.")]))} ])

# ═════════════════════════════ 6 · SHOPPING
task("shopping", "Shopping",
 "Compare the photographs and say why the people might have chosen to shop in these places.",
 "Where do you prefer to go shopping?",
 ("Market", "People buying fruit and fish at the busy Mercado dos Lavradores in Funchal."),
 ("Shopping centre", "Teenagers shopping for clothes in a big, bright shopping centre."),
 [ {"turn": T("Quality and tradition versus convenience and fun — each photo gets a list of reasons, then a label.",
     S("k", "Both photos show people shopping, but in two very different kinds of places.", ["Both photos show", "two very different kinds of"]),
     S("p", "The people at the market have probably chosen it because [[the food is fresh]] and [[it's local]]. You can [[talk to the sellers]], [[try the fruit]] before you buy it, and I imagine some of them have been going to [[the same stall for years]].",
       ["have probably chosen it because", "before you buy it", "I imagine some of them have been going to"],
       wrong=[("There are bananas, oranges and some fish on the tables.", DESCRIBE), ("I go to the market with my grandma.", PREF)]),
     S("q", "The teenagers in the shopping centre, on the other hand, are probably there for [[clothes]] and [[the brands they like]]. It's [[all under one roof]], it's [[air-conditioned]], and they can [[meet their friends]] at the same time. I'd say it's as much [[a social thing]] as a shopping trip.",
       ["on the other hand", "are probably there for", "at the same time", "it's as much", "as"],
       wrong=[("The shopping centre is big and has many shops.", NOCOMP), ("They are definitely buying expensive trainers.", TOOSURE)]),
     S("s", "So the market is about quality and tradition, while the shopping centre is about convenience and fun.",
       ["is about", "while"],
       wrong=[("In conclusion, shopping is fun.", ENDING), ("Both places are also in Funchal.", LONGCMP)])),
    "partner": T("An honest answer, then a turn to grandma and the market — with a reward at the end.",
     S("x", "Ooh, the [[shopping centre]], if I'm honest.", ["if I'm honest"],
       wrong=[("The shopping centre.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "I go to [[Forum Madeira]] with my friends almost every [[Saturday]], mostly just to walk around and chat.", ["almost every"]),
     S("c", "But when my [[grandma]] takes me to the market, I actually really enjoy it — she knows everyone, and they always give me free [[fruit]]!", ["But when", "I actually really enjoy it"],
       wrong=[("And there's a cinema there too.", NOTURN), ("However, markets are more traditional.", GEN)]))},
   {"turn": T("Enjoying the day versus getting things done. The rain joke is a very Madeiran touch.",
     S("k", "The thing both photos have in common is that people are buying things, but for completely different reasons.", ["The thing both photos have in common is that", "for completely different reasons"]),
     S("p", "At the market, I think people are there for [[the experience]] as much as the shopping. There are [[colours everywhere]], [[people shouting prices]], [[exotic fruit]] you can't find anywhere else — and [[tourists]] probably love it. For [[local families]], it might be [[a weekly routine]] they've had for years.",
       ["I think people are there for", "as much as", "you can't find anywhere else", "it might be"],
       wrong=[("The market has a big roof and lots of stalls.", DESCRIBE), ("The market is the oldest in Funchal.", OFFQ)]),
     S("q", "Whereas the shopping centre looks [[more practical]]. The teenagers have probably gone there because [[it's easy]] — they know exactly [[which shops they want]], and they can [[be in and out in an hour]]. They might also just be [[getting out of the rain]]!",
       ["Whereas", "have probably gone there because", "They might also just be"],
       wrong=[("I prefer shopping centres because they have more shops.", PREF), ("The teenagers are wearing jeans.", NOCOMP)]),
     S("s", "So I'd say one is about enjoying the day, and the other is about getting things done.",
       ["So I'd say one is about", "and the other is about"],
       wrong=[("That's all for the photos.", ENDING), ("Both groups are also carrying bags.", LONGCMP)])),
    "partner": T("A cheeky reaction, an unexpected answer, and a mum who's probably right.",
     S("x", "Ha — can I say neither?", ["can I say"],
       wrong=[("Neither.", FLAT), ("Well, that's a good question.", STOCK)]),
     S("a", "[[Online]], to be honest, mostly for clothes.", ["to be honest"]),
     S("r", "I don't really enjoy shopping, so I'd rather just order something and have it delivered to the [[house]].", ["I'd rather just"],
       wrong=[("I shop online because I like the internet.", "Thin. Why?"), ("Online shopping is growing fast.", GEN)]),
     S("c", "Although my [[mum]] says I should at least try on [[shoes]] before I buy them, and she's probably right.", ["Although my mum says", "she's probably right"],
       wrong=[("And it's very fast.", NOTURN), ("However, online shopping is bad for local shops.", GEN)]))},
   {"turn": T("People versus freedom. 'Nobody bothers you' is exactly what a teenager would say.",
     S("k", "In both pictures people are shopping, but the places create a very different atmosphere.", ["create a very different atmosphere"]),
     S("p", "The market looks [[busy and full of life]], so I imagine people choose it because it's [[more personal]]. They can [[ask the sellers questions]], [[find out where the fish comes from]], and maybe [[get a better price]]. For older people especially, it's probably [[part of their social life]].",
       ["looks", "so I imagine people choose it because", "and maybe", "For older people especially"],
       wrong=[("There are many people and many colours in the market.", DESCRIBE), ("All the people at the market are old.", TOOSURE)]),
     S("q", "The shopping centre, by contrast, is [[bright and modern]], and it's the kind of place teenagers like because [[nobody bothers you]]. They can [[wander around for hours]], [[look at everything]] and not buy anything at all. And there's [[a food court]], which is always a good reason to go!",
       ["by contrast", "it's the kind of place", "which is always a good reason to"],
       wrong=[("The shopping centre also sells things, like the market.", LONGCMP), ("I go there every Saturday.", PREF)]),
     S("s", "So the market is about people, whereas the shopping centre is about freedom.", ["is about", "whereas"],
       wrong=[("I think both places are nice.", ENDING), ("Shopping is very popular in Madeira.", OFFQ)])),
    "partner": T("'It depends' — both sides — and one present that proves the second.",
     S("x", "It depends what I'm buying.", ["It depends what"],
       wrong=[("Many places.", "Vague, and not a reaction."), ("That is an interesting question.", STOCK)]),
     S("a", "For [[clothes]], I go to the shopping centre, because there's more choice.", ["because there's more choice"]),
     S("c", "But for presents, I love the little shops in the [[old town]] — you always find something nobody else has.", ["But for", "something nobody else has"],
       wrong=[("And the shopping centre is big.", NOTURN), ("However, small shops are more expensive.", GEN)]),
     S("e", "Last Christmas I bought my [[mum]] a [[hand-painted tile]] there, and she loved it.", ["Last Christmas", "and she loved it"],
       wrong=[("For example, I buy presents.", VAGUE), ("Tiles are typical in Portugal.", "A fact, not a moment.")]))} ])

# ═════════════════════════════ 7 · CELEBRATIONS
task("celebrations", "Celebrations",
 "Compare the photographs and say what the people might be enjoying about these celebrations.",
 "Which kind of celebration do you enjoy more?",
 ("Flower Festival", "A huge crowd watching a colourful parade at the Flower Festival in Funchal."),
 ("Birthday at home", "A small group of friends celebrating a birthday at home, with a cake and candles."),
 [ {"turn": T("Something big versus the people who matter most — a warm idea to end on.",
     S("k", "Both photos show people celebrating, but on very different scales.", ["Both photos show", "on very different scales"]),
     S("p", "At the Flower Festival, I think people are enjoying [[the colours]] and [[the music]] — it's a real show. There are [[thousands of people]], so there's [[an amazing atmosphere]], and I imagine some of them have [[family in the parade]]. It's the kind of day when [[the whole city]] comes out.",
       ["I think people are enjoying", "so there's", "I imagine some of them have", "It's the kind of day when"],
       wrong=[("There are flowers, dancers and a lot of people on the street.", DESCRIBE), ("I go to the Flower Festival every year.", PREF)]),
     S("q", "The birthday party, on the other hand, is much [[smaller and more personal]]. The friends are probably enjoying [[being together]] without [[a big crowd]] around them. It looks like they've made an effort — there's [[a cake]], [[decorations]] — so the birthday girl must feel [[really special]].",
       ["on the other hand", "are probably enjoying", "It looks like they've made an effort", "must feel"],
       wrong=[("The party is in a living room with a sofa.", NOCOMP), ("The cake is definitely chocolate.", TOOSURE)]),
     S("s", "So one is about being part of something big, and the other is about the people who matter most.",
       ["So one is about", "the people who matter most"],
       wrong=[("In conclusion, celebrations are fun.", ENDING), ("Both groups are also smiling.", LONGCMP)])),
    "partner": T("A small answer, a reason from experience, and a birthday that proves it.",
     S("x", "Hmm, that's a hard one.", ["that's a hard one"],
       wrong=[("Small parties.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "Small parties, I think.", ["I think"]),
     S("r", "At big festivals I lose my [[friends]] straight away, and I can never see anything.", ["straight away", "I can never"],
       wrong=[("I like small parties because they're small.", "Circular."), ("Festivals are very crowded.", GEN)]),
     S("e", "My last birthday was just [[five of us]] at home with [[pizza]] and a film, and it was honestly one of the best nights ever.", ["My last birthday", "one of the best nights ever"],
       wrong=[("For example, I had a party.", VAGUE), ("Pizza is popular at parties.", GEN)]))},
   {"turn": T("'The festival is exciting, but the party is probably more fun' — a short ending with a twist.",
     S("k", "What both photos have in common is that everyone looks happy, even though the celebrations are completely different.", ["What both photos have in common is that", "even though"]),
     S("p", "At the parade, I'd imagine what people enjoy most is [[the atmosphere]]. You've got [[music]], [[dancers]], [[flowers everywhere]] — it's [[impossible not to smile]]. For tourists it's probably [[a once-in-a-lifetime thing]], but for locals it might be [[a tradition]] they've enjoyed since they were kids.",
       ["I'd imagine what people enjoy most is", "it's impossible not to", "For tourists", "but for locals"],
       wrong=[("The dancers are wearing traditional costumes.", DESCRIBE), ("Everyone at the festival is a tourist.", TOOSURE)]),
     S("q", "Whereas the party at home seems much [[more relaxed]]. There's [[no pressure]] and [[no crowds]], so they can [[play music they like]] and [[stay up late]]. I think what they're enjoying is [[being with close friends]], [[laughing at silly things]]. They might even be planning to go to the festival later!",
       ["Whereas", "seems much more", "I think what they're enjoying is"],
       wrong=[("I'd rather have a party at home.", PREF), ("There are balloons and a cake on the table.", NOCOMP)]),
     S("s", "So the festival is exciting, but the party is probably more fun.", ["is probably more fun"],
       wrong=[("Those are my thoughts.", ENDING), ("Festivals are important for tourism.", OFFQ)])),
    "partner": T("A big answer with a moment that gives you goosebumps — and a very real downside.",
     S("x", "Big ones, definitely!", ["definitely"],
       wrong=[("Big ones.", FLAT), ("Well, that's a good question.", STOCK)]),
     S("a", "I love [[New Year's Eve]] in Funchal, when everyone's out on the [[seafront]] waiting for the fireworks.", ["when everyone's out"]),
     S("r", "When the [[fireworks]] start, the whole city goes quiet for a second, and then everyone cheers — it gives me goosebumps.", ["goes quiet for a second", "it gives me goosebumps"],
       wrong=[("I like it because it's a big party.", "Thin. What does it feel like?"), ("Madeira's fireworks are world-famous.", GEN)]),
     S("c", "Mind you, getting home afterwards takes about [[three hours]]!", ["Mind you", "getting home afterwards"],
       wrong=[("And the fireworks are beautiful.", NOTURN), ("However, fireworks are bad for animals.", GEN)]))},
   {"turn": T("Watching versus taking part — a clear, clever contrast to finish.",
     S("k", "In both pictures people are celebrating, but I think they're enjoying very different things.", ["I think they're enjoying"]),
     S("p", "The crowd at the Flower Festival are probably enjoying [[the spectacle]]. Everything is [[so colourful]], and I imagine the smell of [[all those flowers]] is incredible. The children in particular look [[amazed]] — maybe it's [[their first time]]. And there's always a moment when the music gets louder and everyone starts dancing in the street.",
       ["are probably enjoying", "I imagine the smell of", "in particular", "maybe it's"],
       wrong=[("There are many flowers of different colours.", DESCRIBE), ("The children have never seen flowers before.", TOOSURE)]),
     S("q", "The friends at the birthday party, by contrast, are enjoying something [[quieter]]. It's probably [[the jokes]], [[the presents]], [[the photos]] they'll keep — the small things. And because it's at home, they can [[be completely themselves]], which is harder in a huge crowd.",
       ["by contrast", "It's probably", "the small things", "which is harder in"],
       wrong=[("The friends are also celebrating, like the crowd.", LONGCMP), ("I love birthday parties.", PREF)]),
     S("s", "So one celebration is about watching, and the other is about taking part.", ["So one", "is about", "and the other is about"],
       wrong=[("I think that's everything.", ENDING), ("Celebrations are part of every culture.", OFFQ)])),
    "partner": T("Both — with different reasons — then a very embarrassing birthday.",
     S("x", "Oh, I like both, but for different reasons.", ["but for different reasons"],
       wrong=[("Both.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "[[Festivals]] are great for the atmosphere.", ["are great for"]),
     S("c", "But for my [[birthday]], I'd always choose something small, because I get embarrassed when everyone's looking at me.", ["But for my", "I'd always choose", "I get embarrassed when"],
       wrong=[("And festivals are colourful.", NOTURN), ("However, small parties are cheaper.", GEN)]),
     S("e", "Last year my friends sang to me in a [[restaurant]], and I wanted the floor to swallow me up.", ["Last year", "I wanted the floor to swallow me up"],
       wrong=[("For example, I had a party.", VAGUE), ("Restaurants often sing for birthdays.", GEN)]))} ])

# ═════════════════════════════ 8 · WORK
task("work", "Work",
 "Compare the photographs and say what might be difficult about working in these places.",
 "Would you rather work indoors or outdoors?",
 ("Harbour", "A fisherman mending nets in the sun at the harbour in Câmara de Lobos."),
 ("Hotel reception", "A young woman working at a hotel reception desk, talking to guests."),
 [ {"turn": T("Hard on the body versus hard on the patience — a summary that sounds like a saying.",
     S("k", "Both photos show people at work, but their jobs couldn't be more different.", ["Both photos show", "couldn't be more different"]),
     S("p", "The fisherman is working [[outside in the sun]], so I think one of the hardest things is [[the weather]]. It's probably [[boiling in summer]] and [[freezing when he goes out at night]]. His job also looks [[physically very tiring]]. He's probably been doing it since he was really young, like his father before him.",
       ["so I think one of the hardest things is", "It's probably", "also looks"],
       wrong=[("The fisherman has a hat and he is holding a net.", DESCRIBE), ("I'd hate to be a fisherman.", PREF)]),
     S("q", "The receptionist, on the other hand, is [[indoors and comfortable]], but her job has different difficulties. She has to [[be polite all day]], even when [[guests are rude or complaining]], and she might have to [[speak several languages]]. That must be [[mentally exhausting]].",
       ["on the other hand", "but her job has different difficulties", "even when", "That must be"],
       wrong=[("The receptionist is wearing a uniform and there's a computer.", NOCOMP), ("The guests are definitely complaining.", TOOSURE)]),
     S("s", "So his job is hard on the body, while hers is hard on the patience.", ["is hard on", "while"],
       wrong=[("In conclusion, all jobs are difficult.", ENDING), ("Both of them are also working.", LONGCMP)])),
    "partner": T("A strong reaction, a dream job as the reason, and a rainy-day exception.",
     S("x", "Outdoors, definitely!", ["definitely"],
       wrong=[("Outdoors.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "I can't imagine sitting at a [[desk]] all day, looking at a computer.", ["I can't imagine"]),
     S("r", "I'd love a job where I'm moving around, like a [[tour guide]] or a [[marine biologist]] out on the boats.", ["I'd love a job where"],
       wrong=[("I prefer outdoors because I like it.", "Circular."), ("Outdoor jobs are healthier.", GEN)]),
     S("c", "Although when it's pouring with [[rain]], maybe an office with a window wouldn't be so bad!", ["Although when", "wouldn't be so bad"],
       wrong=[("And the sun is nice.", NOTURN), ("However, office jobs pay more.", GEN)]))},
   {"turn": T("Risky versus boring. Both jobs are connected to Madeira, which makes the comparison richer.",
     S("k", "What both photos have in common is that the people are working in jobs connected to Madeira — fishing and tourism.", ["What both photos have in common is that", "connected to"]),
     S("p", "The fisherman's biggest difficulty is probably that the work is [[unpredictable]]. Some days there might be [[lots of fish]], and other days [[nothing at all]], so it's hard to [[plan]]. And the sea around here can be [[really rough]], so it could even be [[dangerous]].",
       ["biggest difficulty is probably that", "Some days", "and other days", "it could even be"],
       wrong=[("There are boats and nets in the harbour.", DESCRIBE), ("He never catches any fish.", TOOSURE)]),
     S("q", "Whereas the receptionist has a [[more stable job]], but I imagine it's [[repetitive]]. She probably answers [[the same questions a hundred times a day]] — where's the beach, what time is breakfast. And she might have to work [[nights or weekends]], which is hard if you've got [[a family]].",
       ["Whereas", "but I imagine it's", "She probably answers", "which is hard if"],
       wrong=[("I'd like to work in a hotel one day.", PREF), ("The hotel looks very expensive.", OFFQ)]),
     S("s", "So one job is risky, and the other is maybe a bit boring.", ["So one job is", "and the other is maybe"],
       wrong=[("That's what I think.", ENDING), ("Tourism is Madeira's biggest industry.", OFFQ)])),
    "partner": T("A cautious answer, a practical reason, and an uncle who might change your mind.",
     S("x", "Hmm, honestly?", ["honestly?"],
       wrong=[("Indoors.", FLAT), ("Well, that's a good question.", STOCK)]),
     S("a", "[[Indoors]], I think, like in an office or a lab.", ["I think"]),
     S("r", "I burn really easily in the [[sun]], and I like having everything organised around me.", ["I burn really easily", "I like having"],
       wrong=[("Indoors is better because it's inside.", "Circular."), ("Offices are comfortable.", GEN)]),
     S("c", "Mind you, my [[uncle]]'s a fisherman, and he says he'd go crazy in an office, so maybe I'd change my mind one day.", ["Mind you", "he says he'd go crazy", "maybe I'd change my mind"],
       wrong=[("And offices have air conditioning.", NOTURN), ("However, fishing is a dying profession.", GEN)]))},
   {"turn": T("Fighting the sea versus fighting the complaints — speculation about age and the future adds depth.",
     S("k", "In both pictures people are working, but I think they'd find very different things difficult.", ["I think they'd find"]),
     S("p", "For the fisherman, I'd guess it's [[the hours]]. Fishermen often start [[before sunrise]], and mending nets like that must be [[slow and boring]]. He also looks [[quite old]], so maybe it's getting [[harder for him physically]]. And with [[fewer young people]] doing this job, he might be worried about [[the future]].",
       ["I'd guess it's", "must be", "so maybe it's getting", "he might be worried about"],
       wrong=[("The fisherman is sitting on the ground next to a boat.", DESCRIBE), ("He is definitely going to retire next year.", TOOSURE)]),
     S("q", "The receptionist's job, by contrast, is [[less physical]], but it's [[all about people]]. She has to [[smile all the time]] and [[solve problems quickly]] — a lost key, a noisy room. If the hotel's [[full]], it must be really stressful. And she probably can't just go home when her shift ends if there's still a problem.",
       ["by contrast", "but it's all about", "She has to", "it must be really"],
       wrong=[("The receptionist is also working, like the fisherman.", LONGCMP), ("I'd prefer her job because it's indoors.", PREF)]),
     S("s", "So he's fighting the sea, and she's fighting the complaints.", ["So he's", "and she's"],
       wrong=[("I think both jobs are important.", ENDING), ("Everyone should have a job.", OFFQ)])),
    "partner": T("A condition in the answer, a dream place, and a practical 'though'.",
     S("x", "Outdoors, I think — but not on a [[boat]]!", ["but not on a"],
       wrong=[("Outdoors.", FLAT), ("That is an interesting question.", STOCK)]),
     S("a", "I'd love to work in a [[garden]], or somewhere like the [[Botanical Gardens]].", ["I'd love to work in", "somewhere like"]),
     S("r", "Being surrounded by [[plants]] makes me feel calm, and I'd never be stuck staring at a screen.", ["makes me feel calm", "I'd never be stuck"],
       wrong=[("I like gardens because they have plants.", "Circular."), ("Gardening is good for mental health.", GEN)]),
     S("c", "My [[parents]] say it doesn't pay very well, though, so I'd need a second job!", ["though"],
       wrong=[("And gardens are beautiful.", NOTURN), ("However, gardeners work very hard.", GEN)]))} ])

# ═════════════════════════════ BUILD
def secs_words(t): return len([w for w in t.split() if re.search(r'[A-Za-z0-9]', w)])
def secs(t): return round(secs_words(t)/2.5)
def clean(t): return re.sub(r'\[\[(.*?)\]\]', r'\1', t)
def blank(t): return re.sub(r'\[\[(.*?)\]\]', '___', t)

bad = 0
for tk in TASKS:
    assert len(tk["alts"]) == 3, tk["id"]
    for i, alt in enumerate(tk["alts"]):
        for part, lo, hi, order in (("turn", 50, 60, "kpqs"), ("partner", 20, 30, None)):
            blk = alt[part]
            blk["frame"] = ("\n" if part == "turn" else " ").join(blank(s["t"]) for s in blk["segs"])
            for s in blk["segs"]:
                s["t"] = clean(s["t"])
                for m in s.get("marks", []):
                    if m not in s["t"]: print("MARK", tk["id"], i, part, m); bad += 1
                if s["m"] not in ("k", "a") and len(s.get("wrong", [])) < 2:
                    print("WRONG", tk["id"], i, part, s["m"]); bad += 1
                if re.search(r"\bhere\b.*\bhere\b", s["t"]): print("HERE", tk["id"], i); bad += 1
            ms = "".join(s["m"] for s in blk["segs"]); tot = sum(secs(s["t"]) for s in blk["segs"])
            ok = lo <= tot <= hi and "___" in blk["frame"]
            if order: ok = ok and ms == order
            else: ok = ok and "a" in ms and len(set(ms)) == len(ms) and ("x" not in ms or ms[0] == "x") and len(ms) < 5
            print(f"{'  ' if ok else '!!'} {tk['id']:12} {['Default','Alt 1','Alt 2'][i]:8} {part:8} {ms:5} {tot}s")
            bad += not ok

D = {
 "version": 3, "part": 2,
 "title": "Speaking Part 2 — one pair of photos, one card",
 "note": ("Eight photo pairs set in Madeira. Each has three one-minute turns (Default, Alternative 1, Alternative 2) "
          "and three 30-second answers to the partner's question. Content words are marked in build-part2.py and become "
          "the blanks in each pattern. Photos: add src to each photo when the files are in the repo; until then the card "
          "shows the photo brief."),
 "tip": ("Don't describe the photos — the examiner can see them. Compare in one sentence, then spend the minute on the question."),
 "modes": {
  "turn":    {"label": "1 minute", "limit": 60, "band": [50, 60], "order": ["k", "p", "q", "s"]},
  "partner": {"label": "Partner's question", "limit": 30, "band": [20, 30], "order": ["x", "a", "r", "e", "c"]}
 },
 "moves": {
  "k": {"name": "Compare", "hint": "one sentence: what's the same, and what's different", "ask": "Start by comparing — in one sentence."},
  "p": {"name": "Photo 1", "hint": "answer the question for the first photo — speculate, don't describe", "ask": "Now answer the question for the first photo."},
  "q": {"name": "Photo 2", "hint": "answer it for the second photo — and link it to the first", "ask": "Now the second photo — and link it to the first."},
  "s": {"name": "Sum up", "hint": "one idea that joins both photos", "ask": "Sum up with one idea that joins both photos."},
  "x": {"name": "React", "hint": "how the question makes you feel", "ask": "Now put a reaction in front."},
  "a": {"name": "Answer", "hint": "say it straight", "ask": "Start with the answer."},
  "r": {"name": "Reason", "hint": "why — the part nobody could guess", "ask": "Now say why."},
  "e": {"name": "Example", "hint": "one real moment", "ask": "Now prove it with one real moment."},
  "c": {"name": "Contrast", "hint": "the 'but' that makes it sound real", "ask": "Now add the 'but'."}
 },
 "voices": [{"id": "default", "tab": "Default", "fem": True},
            {"id": "alt1", "tab": "Alternative 1", "fem": False},
            {"id": "alt2", "tab": "Alternative 2", "fem": True}],
 "tasks": TASKS,
 "phraseBank": [
  {"heading": "Comparing — once, quickly", "note": "One sentence, then move on to the question.",
   "phrases": ["Both photos show…, but…", "What both photos have in common is that…", "The thing both photos have in common is…, but the similarities pretty much end there.", "In both pictures…, but I get the feeling…"]},
  {"heading": "Linking the second photo", "note": "The second photo is always compared with the first.",
   "phrases": ["…, on the other hand, …", "Whereas…", "…, by contrast, …", "…has the opposite problem —", "…, though, …"]},
  {"heading": "Speculating", "note": "You can't know from a photo. Say what you think, and how sure you are.",
   "phrases": ["I imagine…", "I'd guess…", "They've probably…", "He might be…", "It could even be that…", "It's quite likely…", "She looks…, so maybe…", "That must be…"]},
  {"heading": "Summing up", "note": "One idea that joins both photos — not 'in conclusion'.",
   "phrases": ["So I'd say it really depends on…", "So one is about…, and the other is about…", "So…, whereas…", "So it's a choice between… and…"]},
  {"heading": "The partner's question", "note": "Thirty seconds: react, answer, one reason or moment.",
   "phrases": ["Oh, definitely…", "It depends what…", "Honestly? …", "The only problem is that…", "Mind you, …", "Last week…, and…"]}
 ]
}
out = sys.argv[1] if len(sys.argv) > 1 else "part2-turn.json"
json.dump(D, open(out, "w"), ensure_ascii=False, indent=1)
print("bad:", bad)
