"""Speaking Part 4 — part4-views.json (v3).

Part 1's deck at Part 4's stakes. The examiner asks; Candidate A reacts,
gives a view and develops it — always widening it out to people in general;
then the examiner turns to Candidate B, who refers to A by name and adds one
point of their own. A: 20–30 s. B: 5–12 s. Key expressions are marked
automatically from BANK; each pattern keeps them and blanks the rest.
"""
import json, re, sys

V = [  # the three pairs: A answers, B joins in
 {"id": "default", "tab": "Default",       "a": "Beatriz", "b": "Tomás", "fem": True,  "bFem": False},
 {"id": "alt1",    "tab": "Alternative 1", "a": "Rodrigo", "b": "Inês",  "fem": False, "bFem": True},
 {"id": "alt2",    "tab": "Alternative 2", "a": "Leonor",  "b": "Diogo", "fem": True,  "bFem": False},
]

BANK = [
 # reacting
 "Honestly?", "Honestly", "To be honest", "It depends", "It's not that simple", "That's a hard one", "Definitely", "Probably", "Absolutely",
 "Not really", "I'm not so sure", "Good question",
 # view
 "I think", "I'd say", "In my opinion", "I believe", "I really don't think", "I'm convinced that", "For me,", "Personally,",
 # generalise
 "Generally speaking", "On the whole", "In general", "Most people", "A lot of people", "Many people", "By and large",
 "For most people", "People tend to", "tend to", "It's usually", "Nowadays", "These days",
 # reason / result
 "because", "The problem is that", "The main reason is", "That's why", "As a result", "which means", "so", "The thing is",
 # example
 "For example", "For instance", "Take", "In my house", "Last year", "Last summer", "At my school", "Where I live",
 # concede
 "Having said that", "Mind you", "Then again", "On the other hand", "Still,", "That said", "Of course", "To be fair", "although", "even though",
 # B joins in
 "I agree with", "I partly agree with", "I see what", "means", "I'm not sure I agree with", "I'd go along with", "made a good point",
 "I'd add that", "What I'd add is", "I'd also say", "For me, though,", "But", "as well",
]

def marks_for(t):
    out, taken = [], []
    for p in sorted(set(BANK), key=len, reverse=True):
        for m in re.finditer(r'(?<![A-Za-z])' + re.escape(p) + r'(?![A-Za-z])', t):
            i, j = m.start(), m.end()
            if any(a < j and i < b for a, b in taken): continue
            taken.append((i, j)); out.append(p); break
    return out, sorted(taken)

def frame_of(t):
    """Keep the key expressions; everything between them becomes one blank."""
    _, spans = marks_for(t)
    out, k = [], 0
    for i, j in spans:
        gap = t[k:i]
        out.append(re.sub(r'[^\s,.;:!?—\-\'’]+(?:[\s\'’\-]+[^\s,.;:!?—\-\'’]+)*', '___', gap) if gap.strip(' ,.;:!?—-') else gap)
        out.append(t[i:j]); k = j
    tail = t[k:]
    out.append(re.sub(r'[^\s,.;:!?—\-\'’]+(?:[\s\'’\-]+[^\s,.;:!?—\-\'’]+)*', '___', tail) if tail.strip(' ,.;:!?—-') else tail)
    f = re.sub(r'___(?:\s*[,—\-]?\s*___)+', '___', "".join(out))
    return re.sub(r'\s{2,}', ' ', f).strip()

# ── why the wrong options are wrong: a pool per move, rotated ──
W = {
 "x": [("That is an interesting question.", "The examiner hears this fifty times a day. React to the question itself."),
       ("Yes.", "A one-word reaction closes the door. Take a position you can defend."),
       ("I don't know, maybe.", "Too vague to build on. Even a cautious view needs a direction.")],
 "g": [("Personally, I always do this every day.", "That's about you. Part 4 asks about people in general — widen it out."),
       ("My best friend thinks the same as me.", "Still personal. The Part 4 move is 'Generally speaking, people…'."),
       ("I think so because I think it's true.", "Circular. Say something about how people in general behave.")],
 "r": [("It's important because it's important.", "Circular. What actually follows from your point?"),
       ("And that's all I think about it.", "It stops the answer instead of developing it."),
       ("There are many reasons for this.", "Name one. A reason the examiner can hear is worth ten 'many reasons'.")],
 "e": [("For example, there are many examples.", "An example has to be one real case — a person, a place, a moment."),
       ("For instance, it happens a lot.", "Vague. Which case? Where? When?"),
       ("For example, the internet exists.", "True but useless. The example has to prove your point.")],
 "c": [("And it's also very good.", "No turn. A concession admits the other side before you finish."),
       ("However, I don't want to talk about that.", "It dodges the question instead of balancing your view."),
       ("On the other hand, I agree with myself.", "A contrast has to swing to the other side, not back to yours.")],
 "o": [("Yes, I agree.", "Too short. Refer to your partner, then add one point of your own."),
       ("I have nothing to add.", "In Part 4 you always have something to add — a reason, an example, a doubt."),
       ("I agree with everything, it was perfect.", "Agreeing isn't enough. Add something new to the discussion.")],
}
_rot = {k: 0 for k in W}
def wrongs(m):
    pool = W[m]; i = _rot[m]; _rot[m] = (i + 1) % len(pool)
    return [{"t": pool[i][0], "why": pool[i][1]}, {"t": pool[(i + 1) % len(pool)][0], "why": pool[(i + 1) % len(pool)][1]}]

CH = []
def chapter(id_, tab, cards): CH.append({"id": id_, "tab": tab, "cards": cards})
def card(id_, q, *alts):
    """alts: three (A-segments, B-refer, B-add, why) tuples."""
    out = {"id": id_, "question": q, "alts": []}
    for i, (A, bn, bo, why) in enumerate(alts):
        segs = [{"m": m, "t": t} for m, t in A]
        out["alts"].append({
            "turn": {"why": why, "segs": segs},
            "partner": {"handover": f"{V[i]['b']}, what do you think?",
                        "why": "Refer to your partner by name, then add one thing of your own.",
                        "segs": [{"m": "n", "t": bn}, {"m": "o", "t": bo}]}})
    return out

# ═══════════════════════════ 1 · TECHNOLOGY
chapter("tech", "Technology", [
 card("phones", "Do you think young people spend too much time on their phones?",
  ([("x", "Honestly? Yes — and I'm including myself!"),
    ("a", "I think most teenagers spend far more time on their phones than they realise."),
    ("g", "Generally speaking, people pick up their phones without even thinking, just out of habit."),
    ("r", "As a result, they lose hours every day that they could spend sleeping or seeing their friends."),
    ("c", "Having said that, phones aren't always a waste of time — they're great for learning things too.")],
   "I agree with Beatriz, especially about the habit part.",
   "Most of my friends check their phones every few minutes, even when we're all together.",
   "A clear view, widened out with 'Generally speaking', a result, and a fair concession at the end."),
  ([("x", "Hmm, it's not that simple."),
    ("a", "It depends what they're doing on them, to be honest."),
    ("g", "On the whole, people criticise teenagers for being on their phones, but adults are just as bad."),
    ("e", "In my house, my dad reads the news on his phone all through dinner, and nobody says anything to him!"),
    ("c", "Still, I think there should be some limits, especially late at night, because it's hard to sleep after hours on a screen.")],
   "I see what Rodrigo means about adults, but I don't think that makes it OK.",
   "Teenagers are still growing, so losing sleep is probably worse for us.",
   "'It's not that simple' buys time and signals a balanced view. The example turns the question back on adults."),
  ([("x", "Probably, yes."),
    ("a", "I think phones have become the centre of most teenagers' lives."),
    ("g", "In general, people our age use them for everything — music, homework, chatting, even shopping."),
    ("r", "The problem is that it's very hard to switch off, because there's always a new message waiting."),
    ("e", "Last summer I tried a week without social media, and I was surprised how much calmer I felt — although I was back online the following Monday!")],
   "I partly agree with Leonor.",
   "But for some people, like my cousin who lives in Jersey, the phone is the only way to stay close to their family.",
   "A cautious reaction, a general point, and a personal experiment as evidence — with a joke against herself.")),
 card("friendship", "Is social media good or bad for friendships?",
  ([("x", "That's a hard one."),
    ("a", "I'd say it's good for keeping friendships, but not so good for making them deeper."),
    ("g", "Most people have hundreds of online friends, but only a few they would actually call if they had a problem."),
    ("r", "The thing is, a like or a comment is easy, so people don't make the effort to meet up."),
    ("c", "On the other hand, group chats help shy people feel included.")],
   "I agree with Beatriz about shy people.",
   "At my school, some people who never talk in class are really funny in the group chat.",
   "Two sides in one view — good for keeping, bad for deepening — then a reason and a concession."),
  ([("x", "Honestly, I think it's mostly bad."),
    ("a", "In my opinion, it makes people compare themselves to others all the time."),
    ("g", "People tend to post only the best moments of their lives, so everyone else's life looks perfect."),
    ("r", "As a result, a lot of teenagers feel left out when they see photos of parties they weren't invited to."),
    ("c", "To be fair, it's not social media's fault — it's how we use it.")],
   "I'm not sure I agree with Rodrigo.",
   "For me, though, social media is how I stay friends with people from my old school, so it's not all bad.",
   "A strong negative view, generalised with 'People tend to', and a fair final line that stops it sounding one-sided."),
  ([("x", "It depends."),
    ("a", "I believe it can be great for friendships, if people use it sensibly."),
    ("g", "These days, friends often live far apart, so social media is how they stay part of each other's lives."),
    ("e", "For example, when my best friend moved to Lisbon, we kept a shared playlist, and it felt like she'd never left."),
    ("c", "Mind you, if you only talk online, the friendship can slowly become a bit empty.")],
   "I agree with Leonor — the playlist idea is lovely.",
   "I'd add that you still need to see each other sometimes, or the jokes stop making sense.",
   "'It depends' + a condition ('if people use it sensibly') is a very Part 4 way to give a nuanced view.")),
 card("ban", "Should schools ban mobile phones?",
  ([("x", "Definitely, at least during lessons."),
    ("a", "I think phones in class are one of the biggest distractions for students."),
    ("g", "Most people can't ignore a notification, even when they're trying to concentrate."),
    ("r", "That's why teachers spend so much time telling students to put their phones away, instead of teaching."),
    ("c", "Having said that, a complete ban would be too much — students need their phones in an emergency, or to call their parents after school.")],
   "I agree with Beatriz about emergencies.",
   "Maybe the best idea is lockers where you leave your phone until the end of the day.",
   "A firm view, a general truth about attention, a result for teachers, and a limit to the ban."),
  ([("x", "I'm not so sure."),
    ("a", "I'd say banning phones doesn't really solve the problem."),
    ("g", "In general, when you ban something, people just find ways to hide it."),
    ("e", "At my school, phones were banned last year, and people simply used them in the toilets instead!"),
    ("c", "Still, I understand why teachers want them out of the classroom — it's really hard to compete with TikTok.")],
   "I see what Rodrigo means, but I still think a ban is better than nothing.",
   "Even if some people cheat, most students would follow the rule.",
   "A sceptical view backed by a funny real example — then understanding for the other side."),
  ([("x", "Hmm, good question."),
    ("a", "For me, the answer is to teach students how to use phones well, not just take them away."),
    ("g", "Nowadays phones are part of normal life, so young people need to learn self-control with them."),
    ("r", "If schools ban them completely, students never practise using them responsibly."),
    ("c", "On the other hand, younger children probably need stricter rules, because they find it harder to stop.")],
   "I'd go along with Leonor on younger children.",
   "My little brother would play games all day if nobody stopped him!",
   "A third option instead of yes or no — that's a sophisticated Part 4 move.")),
 card("lazy", "Do you think technology makes people lazy?",
  ([("x", "In some ways, yes."),
    ("a", "I think it makes everyday life so easy that people don't have to make much effort."),
    ("g", "These days, people order food, watch films and even do their shopping without leaving the sofa."),
    ("r", "As a result, a lot of people move much less than they did in the past."),
    ("c", "Mind you, technology also saves time, and if you use that time well, it can make you more active, not less.")],
   "I agree with Beatriz about moving less.",
   "I'd add that it makes our brains lazy too — nobody remembers phone numbers any more.",
   "'In some ways, yes' gives a partial answer that the rest of the view then explains."),
  ([("x", "Not really, no."),
    ("a", "In my opinion, technology just changes what people spend their energy on."),
    ("g", "People tend to use the time they save for other things, like learning skills online."),
    ("e", "For example, my cousin taught herself to play the guitar completely from videos."),
    ("c", "To be fair, some people just use it to scroll for hours, but that's a choice, not the technology's fault.")],
   "I partly agree with Rodrigo.",
   "But I think the apps are designed to keep us scrolling, so it's not only a personal choice.",
   "A disagreement with the question itself, supported by one clear example."),
  ([("x", "It depends on the person."),
    ("a", "I believe technology can make people lazy, but it can also make them more creative."),
    ("g", "Many people use their phones only to consume things — watching, liking, scrolling."),
    ("r", "The problem is that it's much easier to watch someone else do something than to do it yourself."),
    ("e", "Last year, though, a friend of mine started making short films on her phone, and now she wants to study film.")],
   "I agree with Leonor that it depends on the person.",
   "For me, though, the difference is whether you create things or just watch them.",
   "Two sides in the view, a general problem, and an example that proves the positive side.")),
 card("robots", "Will robots do most jobs in the future?",
  ([("x", "Probably quite a lot of them."),
    ("a", "I think robots and AI will take over many jobs that are repetitive."),
    ("g", "Generally speaking, if a machine can do something faster and cheaper, companies will use it."),
    ("r", "That's why jobs like working in a factory or at a supermarket checkout are already changing."),
    ("c", "Having said that, I don't think robots can replace jobs that need people skills, like nurses or teachers.")],
   "I agree with Beatriz about nurses and teachers.",
   "People want a human being when they're ill or scared, not a machine.",
   "A prediction, a general rule about companies, real evidence, and a clear limit."),
  ([("x", "Honestly, I hope not!"),
    ("a", "In my opinion, people worry too much about robots taking their jobs."),
    ("g", "In general, new technology destroys some jobs but creates new ones that nobody expected."),
    ("e", "For instance, twenty years ago nobody was a social media manager, and now it's a normal job."),
    ("c", "Still, the people who lose their jobs need help to learn new skills, or they'll be left behind.")],
   "I'm not sure I agree with Rodrigo.",
   "The new jobs usually need a lot of studying, so not everyone can switch easily.",
   "An optimistic view backed by history, and a concession about who pays the price."),
  ([("x", "That's a hard one."),
    ("a", "I'd say robots will do many jobs, but humans will still be in charge of them."),
    ("g", "Most people will probably work alongside machines rather than be replaced by them."),
    ("r", "The thing is, someone has to design, repair and control the robots."),
    ("c", "On the other hand, if the change happens too fast, a lot of people could find themselves without work.")],
   "I agree with Leonor about working alongside machines.",
   "That's why I think schools should teach more about technology, so we're ready for it.",
   "A middle position — 'alongside, not instead of' — developed with a reason and a risk.")),
])

# ═══════════════════════════ 2 · SCHOOL & LEARNING
chapter("school", "School & learning", [
 card("teacher", "What makes someone a good teacher?",
  ([("x", "Good question."),
    ("a", "For me, a good teacher is someone who is patient and explains things clearly."),
    ("g", "Most students remember how a teacher made them feel, much more than the actual lessons."),
    ("r", "That's why a teacher who believes in you can change how you feel about a whole subject."),
    ("e", "For example, I used to hate Maths, but last year my teacher never made me feel stupid, and now it's one of my best subjects.")],
   "I agree with Beatriz about believing in students.",
   "I'd add that a good teacher also has a sense of humour — lessons go much faster when you laugh.",
   "A definition, a general truth, a result, and a personal story that proves it."),
  ([("x", "Honestly, I think it's passion."),
    ("a", "In my opinion, the best teachers are the ones who really love their subject."),
    ("g", "People tend to get excited about something when they see someone else excited about it."),
    ("r", "So a teacher who loves History can make even boring dates interesting."),
    ("c", "Mind you, passion isn't enough — they also need to be organised and fair with everyone.")],
   "I see what Rodrigo means about passion.",
   "But I think being fair is even more important — nothing is worse than a teacher with favourites.",
   "One clear quality, generalised, then a condition that stops it being too simple."),
  ([("x", "It depends on the student, to be honest."),
    ("a", "I believe a good teacher is someone who notices that everyone learns differently."),
    ("g", "In general, some people learn by listening, some by doing, and some by talking it through."),
    ("r", "The problem is that with thirty students in a class, it's very hard to help everyone in the right way."),
    ("c", "Still, the best teachers find small ways to do it, like giving different kinds of tasks.")],
   "I agree with Leonor about class sizes.",
   "At my school, the smaller classes always seem to do better in exams.",
   "A thoughtful view about different learners, with a real problem and a realistic solution.")),
 card("online", "Is online learning as good as learning in a classroom?",
  ([("x", "I really don't think so."),
    ("a", "I think online learning is useful, but it can't replace a real classroom."),
    ("g", "Most people find it much harder to concentrate when they're at home in front of a screen."),
    ("r", "As a result, they get distracted by their phones, their family, or even the fridge!"),
    ("c", "Having said that, online courses are brilliant for people who live far from a school, or who want to learn something extra.")],
   "I agree with Beatriz about distractions.",
   "During the lockdowns, I learnt much less than I did at school.",
   "A clear view, a general problem, a funny result, and a fair concession."),
  ([("x", "It depends what you're learning."),
    ("a", "I'd say for some subjects online learning is actually better."),
    ("g", "People tend to learn practical skills, like coding or languages, very well with online videos."),
    ("e", "For example, I learnt most of my English from YouTube and games before I even started studying it properly."),
    ("c", "On the other hand, you can't do a science experiment or a group project properly online.")],
   "I partly agree with Rodrigo.",
   "Online is fine for skills, but you need a classroom to learn how to work with other people.",
   "A condition in the reaction ('It depends what…'), a positive example, and a clear limit."),
  ([("x", "Not really, no."),
    ("a", "In my opinion, what makes learning work is the people, not just the information."),
    ("g", "On the whole, students learn a lot from asking questions and hearing other people's ideas."),
    ("r", "The thing is, online it's easy to stay quiet and never ask anything."),
    ("c", "To be fair, some shy students actually feel more comfortable asking questions in the chat.")],
   "I agree with Leonor that the people matter most.",
   "I'd also say that school is where you make your friends, and you can't do that online.",
   "A deeper view — learning is social — with a concession that shows you've thought about it.")),
 card("homework", "Should students have less homework?",
  ([("x", "Absolutely!"),
    ("a", "I think most students get too much homework, especially before exams."),
    ("g", "Generally speaking, people learn better when they're rested, not exhausted."),
    ("r", "The problem is that after seven hours at school, many students still have two or three hours of homework."),
    ("c", "Of course, some homework is useful, especially practising things like Maths or vocabulary.")],
   "I agree with Beatriz about being rested.",
   "When I have too much homework, I just rush it, so I don't really learn anything.",
   "A strong reaction, a general principle, a concrete problem, and the useful side of homework."),
  ([("x", "I'm not so sure."),
    ("a", "I'd say the amount isn't the real problem — it's what kind of homework it is."),
    ("g", "Most people don't mind work if they can see why it's useful."),
    ("e", "For instance, last term we had to interview our grandparents for History, and everyone loved it."),
    ("c", "Still, if every teacher gives homework on the same day, it's too much, however good it is.")],
   "I see what Rodrigo means about useful homework.",
   "But I think teachers should also talk to each other, so we don't get five tests in one week.",
   "Reframing the question — not how much, but what kind — then a great example."),
  ([("x", "Probably, yes."),
    ("a", "I believe young people need more free time than they get at the moment."),
    ("g", "These days, teenagers are busier than ever, with school, sport, music lessons and homework."),
    ("r", "As a result, a lot of them hardly have time to rest or see their friends during the week."),
    ("c", "Having said that, a small amount of homework helps you remember what you learnt in class.")],
   "I agree with Leonor about free time.",
   "Free time isn't wasted time — it's when we're creative.",
   "A view about balance, generalised to teenagers, with a fair concession.")),
 card("alone", "Is it better to study alone or with friends?",
  ([("x", "It depends on what you're studying."),
    ("a", "I think studying alone is better when you need to concentrate."),
    ("g", "Most people get distracted when they're with friends, because they start chatting."),
    ("r", "That's why I usually study alone for tests, but with friends for projects."),
    ("c", "On the other hand, friends can explain things in a simpler way than teachers sometimes.")],
   "I agree with Beatriz about friends explaining things.",
   "Sometimes my friend explains something in two minutes that I didn't understand in a whole lesson.",
   "Two situations, two answers — a very balanced Part 4 view."),
  ([("x", "Definitely with friends, for me."),
    ("a", "In my opinion, studying with friends makes it less boring and more motivating."),
    ("g", "People tend to work harder when they don't want to let the group down."),
    ("e", "For example, before our English exam, four of us met at the library every Saturday, and we all did well."),
    ("c", "Mind you, it only works if everyone is serious about it — one person who isn't can ruin it.")],
   "I partly agree with Rodrigo.",
   "It works for him, but I'm the kind of person who needs total silence.",
   "A firm preference, a general reason, proof from experience, and a condition."),
  ([("x", "Honestly, a bit of both."),
    ("a", "I believe the best way is to learn things alone first, and then test yourself with friends."),
    ("g", "In general, you only really understand something when you can explain it to someone else."),
    ("r", "So studying in a group is a good way to find out what you don't know yet."),
    ("c", "Still, you need to do the hard thinking on your own first, or the group just copies from one person.")],
   "I agree with Leonor about explaining things.",
   "When I explain something to my little sister, I realise how much I actually know.",
   "A two-step method as the view, with a principle about learning behind it.")),
 card("cook", "Should everyone learn to cook at school?",
  ([("x", "Definitely!"),
    ("a", "I think cooking is one of the most useful skills you can learn."),
    ("g", "A lot of young people leave home without knowing how to make even a simple meal."),
    ("r", "As a result, they spend a lot of money on fast food, which isn't good for their health either."),
    ("c", "Having said that, schools already have a very full timetable, so it's hard to find time for new subjects.")],
   "I agree with Beatriz about fast food.",
   "I'd add that cooking together is a great way to learn about other cultures.",
   "A strong yes, a general problem, its results, and a practical concession."),
  ([("x", "I'm not so sure."),
    ("a", "In my opinion, cooking is something you learn best at home, not at school."),
    ("g", "In most families, recipes are passed down from parents and grandparents."),
    ("e", "For example, my grandma taught me to make bolo do caco, and I'd never learn that in a classroom."),
    ("c", "To be fair, not every family has time to teach cooking, so school could help those students.")],
   "I see what Rodrigo means about families.",
   "But school could teach the basics, like healthy eating and food safety.",
   "A different angle — home versus school — with a lovely local example."),
  ([("x", "Yes, I think so."),
    ("a", "I believe learning to cook would help young people be healthier and more independent."),
    ("g", "These days, people eat a lot of ready meals, and many don't really know what's in them."),
    ("r", "The problem is that you can't make healthy choices if you don't understand food."),
    ("c", "Mind you, some students might not be interested, so the lessons would need to be practical and fun.")],
   "I agree with Leonor about being independent.",
   "My older brother went to university in Lisbon and lived on pasta for a whole year!",
   "A view linked to health and independence, with a realistic condition.")),
])

# ═══════════════════════════ 3 · WORK & MONEY
chapter("money", "Work & money", [
 card("parttime", "Should teenagers have part-time jobs?",
  ([("x", "It depends on the job."),
    ("a", "I think a small part-time job can be really good for teenagers."),
    ("g", "Generally speaking, people value money much more when they've earned it themselves."),
    ("r", "It also teaches you to be responsible and to talk to adults with confidence."),
    ("c", "Having said that, school should come first, so it should only be a few hours at the weekend.")],
   "I agree with Beatriz about the weekend.",
   "In the summer, a lot of teenagers here work in cafés, and I think that's a great experience.",
   "A conditional yes, a general truth about money, extra benefits, and a clear limit."),
  ([("x", "Honestly, not during the school year."),
    ("a", "In my opinion, teenagers already have enough pressure with school and exams."),
    ("g", "Most people find it very hard to work and study at the same time."),
    ("r", "As a result, their grades can drop, and they're tired all the time."),
    ("c", "Still, a summer job is a different thing — it gives you experience without affecting your studies.")],
   "I partly agree with Rodrigo.",
   "But for some families, a teenager's job helps pay the bills, so it isn't always a choice.",
   "A firm no with a clear condition, and a concession that separates summer from term time."),
  ([("x", "Probably, yes."),
    ("a", "I believe a part-time job teaches things that school can't."),
    ("g", "On the whole, people learn how the real world works when they have to deal with customers and bosses."),
    ("e", "Last summer I helped at my aunt's shop, and I learnt more about patience than in a whole year at school!"),
    ("c", "Mind you, the job has to be safe, and the hours have to be reasonable.")],
   "I agree with Leonor about patience.",
   "I'd add that having a job also shows you how hard your parents work.",
   "A positive view, a general point, and a real experience with a joke.")),
 card("enjoy", "Is it more important to enjoy your job or to earn a lot of money?",
  ([("x", "For me, enjoying it, definitely."),
    ("a", "I think if you hate your job, no amount of money can make you happy."),
    ("g", "Most people spend more time at work than anywhere else, so it has a huge effect on their lives."),
    ("r", "That's why people who love their jobs usually seem happier and healthier."),
    ("c", "Of course, you still need enough money to live comfortably, so it's about finding a balance.")],
   "I agree with Beatriz about finding a balance.",
   "My uncle earns a lot, but he's always stressed and never sees his children.",
   "A clear priority, a general reason, a result, and the practical limit."),
  ([("x", "That's a hard one."),
    ("a", "I'd say money matters more than people like to admit."),
    ("g", "In general, it's easy to say 'follow your dreams' when you don't have to pay rent."),
    ("r", "The problem is that a lot of enjoyable jobs don't pay enough to live on, especially on an island like Madeira."),
    ("c", "To be fair, if you can find something you enjoy and it pays well, that's obviously the best of both worlds.")],
   "I see what Rodrigo means about rent.",
   "But I think you can be happy with less money if you love what you do.",
   "A more realistic view that challenges the obvious answer — examiners like that."),
  ([("x", "It depends on the person."),
    ("a", "I believe different people want different things from their jobs."),
    ("g", "Some people are happy doing any job as long as it pays well, while others need to feel it's important."),
    ("e", "For example, my mum is a nurse — she doesn't earn a fortune, but she says she'd never do anything else."),
    ("c", "Still, I think most people would choose a job they enjoy if they could afford to.")],
   "I agree with Leonor about different people.",
   "For me, though, I'd like a job I enjoy — even if I have to live in a smaller flat!",
   "Two types of people, one real example, and a general conclusion.")),
 card("manage", "Should young people learn how to manage money at school?",
  ([("x", "Absolutely."),
    ("a", "I think managing money is one of the most important life skills, and schools hardly teach it."),
    ("g", "A lot of young people don't understand things like saving, bank accounts or loans."),
    ("r", "As a result, some of them get into debt as soon as they get their first credit card."),
    ("c", "Having said that, parents should also talk about money at home, not leave it all to schools.")],
   "I agree with Beatriz about talking at home.",
   "In my family, we never talk about money, so I'd love to learn it at school.",
   "A strong view, a gap in knowledge, a real consequence, and shared responsibility."),
  ([("x", "Definitely."),
    ("a", "In my opinion, it would be more useful than some of the things we learn now."),
    ("g", "Most people will use budgeting every month of their lives, but they might never use some Maths formulas again."),
    ("e", "For example, I didn't know what taxes were until my brother got his first job and complained about his salary!"),
    ("c", "Mind you, I wouldn't want it to replace Maths — it could be part of Maths lessons.")],
   "I agree with Rodrigo that it could be part of Maths.",
   "Real examples, like planning a holiday budget, would make Maths more interesting too.",
   "A comparison with the current curriculum, a funny example, and a practical suggestion."),
  ([("x", "Yes, I think so."),
    ("a", "I believe it would help young people make better decisions in the future."),
    ("g", "These days, it's very easy to spend money online without really noticing."),
    ("r", "The problem is that apps and games are designed to make you spend, especially young people."),
    ("c", "Still, you learn a lot about money by making small mistakes yourself.")],
   "I partly agree with Leonor.",
   "Small mistakes are fine, but big ones, like debt, can take years to fix.",
   "A view about the future, a modern problem, and a thoughtful concession.")),
 card("save", "Why do some people find it hard to save money?",
  ([("x", "Good question."),
    ("a", "I think the main reason is that spending is just so easy now."),
    ("g", "Most people pay with their phone or card, so they don't really feel the money leaving."),
    ("r", "As a result, lots of small purchases add up without anyone noticing."),
    ("e", "For instance, I once added up my snacks from the school café, and it was nearly thirty euros in a month!")],
   "I agree with Beatriz about small purchases.",
   "I'd add that adverts are everywhere, so we always feel like we need something new.",
   "One main reason, a general cause, its result — and a real example with a number."),
  ([("x", "It depends on the person."),
    ("a", "In my opinion, for some people it isn't about habits — they just don't earn enough."),
    ("g", "In general, when prices go up, families spend almost everything on basic things like rent and food."),
    ("r", "So it's unfair to say that people who can't save are always careless."),
    ("c", "To be fair, some people with good salaries also find it hard, because they spend more when they earn more.")],
   "I agree with Rodrigo that it's not always people's fault.",
   "Life on the island is quite expensive, so a lot of families find it hard.",
   "A socially aware view that challenges the question's assumption."),
  ([("x", "Honestly, because saving is boring!"),
    ("a", "I'd say people find it hard because the reward is so far away."),
    ("g", "People tend to choose something nice now instead of something better later."),
    ("r", "The thing is, it's easy to buy a new game today, but hard to imagine a car in five years."),
    ("c", "Having said that, if you have a clear goal, like a trip with friends, saving becomes much easier.")],
   "I agree with Leonor about having a goal.",
   "Last year I saved for a new bike, and I stopped buying snacks without even thinking about it.",
   "A funny reaction with a serious point behind it — then a way to solve the problem.")),
 card("toomuch", "Do you think people work too much these days?",
  ([("x", "Yes, I really do."),
    ("a", "I think a lot of adults work so much that they hardly have time for their families."),
    ("g", "These days, people can answer work emails from anywhere, so work follows them home."),
    ("r", "As a result, they never completely switch off, even at weekends."),
    ("c", "Of course, some people have no choice, because they need the money.")],
   "I agree with Beatriz about emails.",
   "My mum answers messages from work at dinner, and it drives my dad crazy.",
   "A clear view, a modern cause, a result, and understanding for people with no choice."),
  ([("x", "It's not that simple."),
    ("a", "I'd say it depends a lot on the job and the country."),
    ("g", "In general, people in some jobs, like doctors or restaurant workers, have very long hours."),
    ("e", "For example, my uncle works in a hotel, and in summer he sometimes works six days a week."),
    ("c", "On the other hand, some companies now let people work from home, which gives them more free time.")],
   "I see what Rodrigo means about hotels.",
   "Tourism is great for Madeira, but it's hard work for the people in it.",
   "A nuanced start, a general pattern, a local example, and a positive change."),
  ([("x", "Probably, yes."),
    ("a", "I believe people work too much because everyone expects them to be busy all the time."),
    ("g", "Many people feel guilty when they rest, as if being tired is something to be proud of."),
    ("r", "The problem is that working too much can make people ill and unhappy."),
    ("c", "Still, I think my generation will want a better balance — we've seen how stressed our parents are.")],
   "I agree with Leonor about feeling guilty.",
   "I'd add that rest is part of doing a good job, not the opposite.",
   "A view about attitudes, not just hours — and a hopeful look at the future.")),
])

# ═══════════════════════════ 4 · HEALTH & SPORT
chapter("health", "Health & sport", [
 card("exercise", "Do you think people exercise enough these days?",
  ([("x", "Not really, no."),
    ("a", "I think most people exercise much less than they should."),
    ("g", "Generally speaking, people are very busy, and exercise is usually the first thing they drop."),
    ("r", "As a result, a lot of people only move from the car to the office and back."),
    ("c", "Having said that, more and more people are running or going to the gym than a few years ago.")],
   "I agree with Beatriz about being busy.",
   "Where I live, lots of people walk the levadas at the weekend, but not during the week.",
   "The old Part 4's best answer, rewritten for a teenager: view, generalise, result, concede."),
  ([("x", "It depends who you mean."),
    ("a", "In my opinion, young people exercise quite a lot, but adults don't."),
    ("g", "Most teenagers do sport at school or with friends, but when people start working, they stop."),
    ("e", "For example, my dad used to play football every week, and now he says he's too tired."),
    ("c", "To be fair, adults have more responsibilities, so it's harder for them to find time.")],
   "I partly agree with Rodrigo.",
   "But I think a lot of teenagers stop doing sport too, especially when exams get closer.",
   "A distinction between groups, a pattern, a real example, and understanding."),
  ([("x", "Probably not."),
    ("a", "I believe people know exercise is important, but they find it hard to make it a habit."),
    ("g", "People tend to start with a lot of energy in January and give up by March!"),
    ("r", "The thing is, exercise only works if you find something you actually enjoy."),
    ("c", "Mind you, even walking to school or taking the stairs counts, and a lot of people forget that.")],
   "I agree with Leonor about enjoying it.",
   "I hated running, but I love dancing, and it's just as good for you.",
   "A view about habits, a funny general truth, a reason, and a practical tip.")),
 card("fastfood", "Why is fast food so popular?",
  ([("x", "Honestly, because it's quick and cheap."),
    ("a", "I think the main reason is that people don't have much time to cook any more."),
    ("g", "Most people finish work late and just want something fast and easy."),
    ("r", "It's also designed to taste good, so people want more of it."),
    ("c", "Having said that, a lot of people know it's unhealthy, and they feel guilty afterwards.")],
   "I agree with Beatriz about time.",
   "I'd add that for teenagers, fast-food places are also somewhere cheap to meet friends.",
   "A reason in the reaction, a general cause, a second reason, and a concession."),
  ([("x", "That's a good question."),
    ("a", "In my opinion, advertising has a lot to do with it."),
    ("g", "In general, young people see adverts for burgers and pizza everywhere — on TV, online, even at football matches."),
    ("r", "So they start to think it's normal to eat it all the time."),
    ("c", "To be fair, some fast-food chains now sell salads and healthier options too.")],
   "I see what Rodrigo means about adverts.",
   "But I think we choose it because it tastes good, not only because of the adverts.",
   "A less obvious reason — advertising — with a result and a fair update."),
  ([("x", "It's not that simple."),
    ("a", "I'd say it's popular because it's predictable — you always know what you're getting."),
    ("g", "People tend to like food that's the same everywhere, especially when they're travelling."),
    ("e", "For example, tourists in Funchal often go to fast-food places, even though there's amazing local food."),
    ("c", "Still, I think more people are starting to prefer fresh, local food.")],
   "I agree with Leonor about tourists.",
   "It's a shame, because they miss things like espetada and bolo do caco!",
   "An original reason, generalised, a local example, and a hopeful trend.")),
 card("compulsory", "Should sport be compulsory at school?",
  ([("x", "Yes, I think so."),
    ("a", "I think sport at school is important for students' health."),
    ("g", "A lot of young people sit down for most of the day — at school, doing homework, and on their phones."),
    ("r", "That's why PE might be the only exercise some of them get all week."),
    ("c", "Having said that, not everyone enjoys team sports, so schools should offer different options.")],
   "I agree with Beatriz about different options.",
   "Things like dance or climbing would be great for people who hate football.",
   "A clear yes, a general problem, a strong result, and a sensible condition."),
  ([("x", "I'm not so sure."),
    ("a", "In my opinion, forcing people to do sport can make them hate it."),
    ("g", "Most people enjoy things more when they choose them themselves."),
    ("e", "For example, a friend of mine was always last in PE, and now she refuses to do any sport at all."),
    ("c", "Still, I understand why schools want everyone to move a bit during the day.")],
   "I partly agree with Rodrigo.",
   "I think it's about how PE is taught — if it's fun, people won't hate it.",
   "A sceptical view, a general truth, a sad example, and understanding."),
  ([("x", "Definitely."),
    ("a", "I believe PE teaches much more than just fitness."),
    ("g", "On the whole, sport teaches people how to work in a team and how to lose."),
    ("r", "The thing is, learning to lose without getting angry is a really useful life skill."),
    ("c", "Mind you, PE teachers need to make sure the less sporty students don't feel embarrassed.")],
   "I agree with Leonor about losing.",
   "I'd also say sport is good for stress, especially before exams.",
   "A broader view of what PE teaches, with an original point about losing.")),
 card("footballers", "Are professional footballers paid too much?",
  ([("x", "Honestly? Yes, I think so."),
    ("a", "I think it's strange that footballers earn so much more than nurses or teachers."),
    ("g", "Most people do far more important jobs for a tiny fraction of the money."),
    ("r", "As a result, a lot of young people think football is the only way to be successful."),
    ("c", "Having said that, their careers are very short, and they're under huge pressure.")],
   "I agree with Beatriz about nurses and teachers.",
   "But I think the fans pay the salaries, so it's partly our fault!",
   "A strong view with a comparison, a result for young people, and a fair concession."),
  ([("x", "Not really, no."),
    ("a", "In my opinion, they're paid what the market says they're worth."),
    ("g", "In general, millions of people watch football, so clubs make huge amounts of money."),
    ("r", "So it's normal that the best players get a big part of it."),
    ("e", "For example, Cristiano Ronaldo, who's from here, brings money and tourists to the whole island.")],
   "I see what Rodrigo means about Ronaldo.",
   "He also helps his community, which not all rich footballers do.",
   "A counter-view about markets, a logical reason, and a local example."),
  ([("x", "It's a hard one."),
    ("a", "I'd say the very top players are paid too much, but most footballers aren't."),
    ("g", "People tend to think of the famous stars, but most professional players earn quite normal salaries."),
    ("r", "The problem is that we only hear about the few who earn millions."),
    ("c", "Still, I think the richest clubs should give more money to local sport and young players.")],
   "I agree with Leonor about local sport.",
   "The football pitches at my school are in terrible condition.",
   "A careful distinction — top players versus the rest — and a practical suggestion.")),
 card("harder", "Is it harder to be healthy today than in the past?",
  ([("x", "In some ways, yes."),
    ("a", "I think modern life makes it harder to eat well and move enough."),
    ("g", "These days, most people work sitting down, and unhealthy food is everywhere and cheap."),
    ("r", "As a result, you have to make much more effort to stay healthy."),
    ("c", "On the other hand, we know much more about health now, and we have better doctors.")],
   "I agree with Beatriz about knowing more.",
   "My grandparents didn't even know smoking was bad for you when they were young.",
   "A partial yes, general causes, a result, and the other side of history."),
  ([("x", "I'm not so sure."),
    ("a", "In my opinion, in some ways it's easier now."),
    ("g", "In general, people have more information, more gyms and more healthy food to choose from than ever."),
    ("e", "For example, my grandad worked in the fields all day as a boy and often didn't have enough to eat."),
    ("c", "To be fair, the problem today is having too much choice, not too little.")],
   "I partly agree with Rodrigo.",
   "Having choices is good, but only if you make the right ones.",
   "A challenge to the question, supported by a family example."),
  ([("x", "Probably, yes."),
    ("a", "I believe the biggest difference is stress."),
    ("g", "Many people, including teenagers, feel much more pressure than people did in the past."),
    ("r", "The thing is, stress affects your sleep, your eating and your mood."),
    ("c", "Mind you, people talk about mental health much more openly now, which is a very good thing.")],
   "I agree with Leonor about stress.",
   "I'd add that social media makes it worse, because you always compare yourself to others.",
   "An unexpected angle — mental health — with a hopeful concession.")),
])

# ═══════════════════════════ 5 · ENVIRONMENT & FUTURE
chapter("future", "Environment & future", [
 card("help", "What can young people do to help the environment?",
  ([("x", "Quite a lot, actually."),
    ("a", "I think young people can make a difference with small everyday changes."),
    ("g", "Most people could walk more, recycle properly and waste less food without much effort."),
    ("r", "And because young people influence their families, those habits spread at home too."),
    ("c", "Having said that, individuals can only do so much — governments and companies have to change too.")],
   "I agree with Beatriz about influencing families.",
   "I made my family start recycling, and now my dad is stricter about it than me!",
   "An optimistic view, general actions, a knock-on effect, and a bigger-picture concession."),
  ([("x", "Honestly, I think they can speak up."),
    ("a", "In my opinion, the most powerful thing young people can do is make their voices heard."),
    ("g", "In general, politicians listen when lots of people care about the same issue."),
    ("e", "For example, students around the world organised climate strikes, and it put the environment in the news everywhere."),
    ("c", "Still, protesting isn't enough on its own — you also have to change how you live.")],
   "I see what Rodrigo means about protests.",
   "But I think some people protest and then fly on holiday three times a year.",
   "A view about voice and action, a real example, and a condition."),
  ([("x", "It depends on where they live."),
    ("a", "I believe young people can help most by looking after their local environment."),
    ("g", "People tend to protect places they feel connected to."),
    ("e", "For example, last year my class cleaned a beach near Funchal, and we collected three big bags of plastic."),
    ("c", "Mind you, it's a bit depressing, because the next week there was more rubbish again.")],
   "I agree with Leonor about local places.",
   "I'd add that on an island, you really see the plastic that comes in from the sea.",
   "A local focus, a general truth, a real action, and an honest concession.")),
 card("fashion", "Is fast fashion a problem we should care about?",
  ([("x", "Definitely."),
    ("a", "I think fast fashion is a much bigger problem than most people realise."),
    ("g", "A lot of people buy clothes they only wear a few times and then throw away."),
    ("r", "As a result, huge amounts of clothes end up as rubbish, and making them uses lots of water."),
    ("c", "Having said that, cheap clothes are the only option for some families, so it's not easy to just stop.")],
   "I agree with Beatriz about families.",
   "Second-hand shops could be the answer — they're cheap and better for the planet.",
   "A clear view, a general habit, its results, and a fair point about money."),
  ([("x", "Yes, but it's not that simple."),
    ("a", "In my opinion, the biggest problem is how the workers are treated."),
    ("g", "In general, people who make cheap clothes work very long hours for very little money."),
    ("r", "So when we pay five euros for a T-shirt, someone else is really paying the price."),
    ("c", "To be fair, it's hard to know which brands are really ethical and which just say they are.")],
   "I see what Rodrigo means about the workers.",
   "I didn't think about that before, to be honest.",
   "A different angle — people, not just the planet — with a powerful image."),
  ([("x", "Probably, yes."),
    ("a", "I believe teenagers are part of the problem, but also part of the solution."),
    ("g", "People our age follow trends very quickly, so shops change their clothes every few weeks."),
    ("r", "The thing is, if we stopped buying so much, the shops would have to change."),
    ("e", "For example, my friends and I started swapping clothes instead of buying new ones, and it's actually fun.")],
   "I agree with Leonor about swapping.",
   "I'd add that it's cool to have something nobody else is wearing.",
   "Honest about her own generation, a reason, and a solution she's tried.")),
 card("transport", "Should public transport be free for teenagers?",
  ([("x", "Yes, definitely."),
    ("a", "I think free buses would help teenagers be more independent."),
    ("g", "A lot of young people depend on their parents for lifts, which isn't always possible."),
    ("r", "As a result, some of them miss out on sport or activities after school."),
    ("c", "Having said that, someone has to pay for it, probably through taxes.")],
   "I agree with Beatriz about independence.",
   "And it would mean fewer cars outside schools in the morning.",
   "A clear view, a general problem, a real consequence, and the cost."),
  ([("x", "It's not that simple."),
    ("a", "In my opinion, it should be free for teenagers who can't afford it, but not for everyone."),
    ("g", "Most families can pay for a bus pass, so the money should go to the ones who can't."),
    ("r", "That way, the buses could also be improved with the money saved."),
    ("c", "Still, checking who deserves it could be complicated and expensive.")],
   "I partly agree with Rodrigo.",
   "But if it's free for everyone, nobody feels embarrassed about using it.",
   "A middle position — targeted help — with a practical problem."),
  ([("x", "I'm not so sure."),
    ("a", "I believe the real problem isn't the price — it's that the buses don't go where people need them."),
    ("g", "People tend to use public transport when it's frequent and reliable."),
    ("e", "For example, where my grandparents live, there's only one bus every two hours, so free or not, nobody uses it."),
    ("c", "Mind you, a free pass would still help in the city, where the buses are good.")],
   "I agree with Leonor about reliable buses.",
   "Free buses are useless if they're always late!",
   "Reframing the problem, a general truth, a local example, and a concession.")),
 card("tourism", "Is tourism good or bad for places like islands?",
  ([("x", "Both, to be honest."),
    ("a", "I think tourism brings a lot of money and jobs, but it also brings problems."),
    ("g", "Most islands depend on tourists, because there aren't many other industries."),
    ("r", "The problem is that too many tourists can make houses more expensive and roads more crowded."),
    ("e", "For example, in Funchal, a lot of flats in the centre are now rented to tourists, so local families can't find homes.")],
   "I agree with Beatriz about houses.",
   "My cousin has been looking for a flat for a year and still can't find one she can afford.",
   "Both sides at once, a general dependence, a real problem, and a local example."),
  ([("x", "Mostly good, I'd say."),
    ("a", "In my opinion, without tourism, life on an island would be much harder."),
    ("g", "In general, tourists spend money in restaurants, shops and hotels, which gives jobs to local people."),
    ("r", "So a lot of families depend on tourism, directly or indirectly."),
    ("c", "Still, it needs to be controlled, so that the nature and the traditions are protected.")],
   "I see what Rodrigo means about jobs.",
   "But I think we need other industries too, in case tourists stop coming one day.",
   "A mostly positive view, a clear mechanism, and a condition."),
  ([("x", "It depends how it's managed."),
    ("a", "I believe tourism is good when it respects the place and the people who live there."),
    ("g", "People tend to love places like Madeira because they're natural and quiet."),
    ("r", "The thing is, if too many people come, it stops being natural and quiet."),
    ("c", "Having said that, tourists also help protect nature, because they pay to visit it.")],
   "I agree with Leonor about respecting the place.",
   "Some levadas are so busy now that it's hard to enjoy them.",
   "A conditional view, a paradox, and a concession that shows balance.")),
 card("fifty", "Will life be better or worse in fifty years?",
  ([("x", "Hmm, that's a hard one."),
    ("a", "I think some things will be better, like medicine and technology."),
    ("g", "Generally speaking, every generation has lived longer and healthier lives than the one before."),
    ("r", "So there's a good chance that diseases we can't cure today will be curable."),
    ("c", "Having said that, climate change could make life much harder, especially for islands like ours.")],
   "I agree with Beatriz about medicine.",
   "But I'm worried about the sea level, because a lot of Funchal is right by the water.",
   "A partial optimism, a historical pattern, a hopeful result, and a local worry."),
  ([("x", "Honestly, I'm optimistic."),
    ("a", "In my opinion, young people care more about the planet than any generation before."),
    ("g", "In general, when people really care about a problem, they find solutions."),
    ("e", "For example, electric cars were rare ten years ago, and now you see them everywhere."),
    ("c", "Still, we need to move much faster, or it won't be enough.")],
   "I partly agree with Rodrigo.",
   "I'm optimistic too, but I think it depends on what governments decide.",
   "An optimistic view, a principle, evidence from change, and urgency."),
  ([("x", "It depends on what we do now."),
    ("a", "I believe the future isn't decided yet — it depends on the choices we make."),
    ("g", "People tend to think the future just happens, but it's the result of millions of small decisions."),
    ("r", "That's why things like voting and what we buy matter."),
    ("c", "Mind you, I think technology will make life easier, but not necessarily happier.")],
   "I agree with Leonor about choices.",
   "I'd add that my generation will be the ones making those choices.",
   "A thoughtful 'it depends', a big idea about choices, and a subtle final point.")),
])

# ═══════════════════════════ 6 · PEOPLE & SOCIETY
chapter("people", "People & society", [
 card("friends", "Is it better to have lots of friends or a few close ones?",
  ([("x", "A few close ones, definitely."),
    ("a", "I think a few real friends are worth more than lots of people you hardly know."),
    ("g", "Most people only have two or three friends they can really trust."),
    ("r", "That's why, when something goes wrong, it's those few people you call."),
    ("c", "Having said that, having lots of friends is fun, especially for going out and meeting new people.")],
   "I agree with Beatriz about trust.",
   "I'd add that close friends are the ones who tell you the truth, even when you don't want to hear it.",
   "A firm view, a general truth, a result, and the fun side of many friends."),
  ([("x", "It depends on your personality."),
    ("a", "In my opinion, some people need a big group, and others are happier with one or two friends."),
    ("g", "In general, outgoing people get energy from being with lots of people."),
    ("e", "For example, my brother has about fifty friends, but I prefer my small group — we've known each other since we were six."),
    ("c", "Still, I think everyone needs at least one person who really knows them.")],
   "I see what Rodrigo means about personality.",
   "I'm definitely more like his brother — I love big groups!",
   "A view based on personality types, a family example, and a general conclusion."),
  ([("x", "Honestly, a bit of both."),
    ("a", "I believe the best thing is to have a few close friends and a wider group too."),
    ("g", "People tend to need different friends for different things."),
    ("r", "The thing is, you might talk about problems with one friend and just have fun with others."),
    ("c", "Mind you, it takes time to keep a lot of friendships going, and time is something teenagers don't have much of!")],
   "I agree with Leonor about different friends.",
   "My football friends and my school friends are completely different, and I like both.",
   "A balanced 'both' answer, a general reason, and a funny concession.")),
 card("parents", "Do teenagers and parents understand each other?",
  ([("x", "Not always!"),
    ("a", "I think it's hard for parents to understand what it's like to be a teenager today."),
    ("g", "Most parents grew up without smartphones or social media, so they don't really understand the pressure."),
    ("r", "As a result, they sometimes worry about the wrong things."),
    ("c", "Having said that, teenagers don't always try to understand their parents either — they have stress too.")],
   "I agree with Beatriz about parents having stress.",
   "My dad works really long hours, and I only realised how tired he was last year.",
   "A view about the generation gap, a general cause, a result, and a fair turn."),
  ([("x", "It depends on the family."),
    ("a", "In my opinion, families who talk a lot understand each other much better."),
    ("g", "In general, problems get bigger when people stop talking."),
    ("e", "For example, in my family we eat together every evening, and it's when we talk about everything."),
    ("c", "Still, some things teenagers prefer to talk about with friends, and that's normal.")],
   "I partly agree with Rodrigo.",
   "Eating together helps, but only if nobody is looking at their phone!",
   "A condition, a general truth, a real habit, and a normal limit."),
  ([("x", "More than people think, actually."),
    ("a", "I believe parents understand more than teenagers give them credit for."),
    ("g", "People tend to forget that their parents were teenagers once too."),
    ("r", "The thing is, the details are different, but the feelings are the same — being nervous, falling out with friends."),
    ("c", "Mind you, it's still embarrassing when they try to use teenage slang!")],
   "I agree with Leonor about the slang!",
   "My mum tried to say something was 'fire' last week, and we couldn't stop laughing.",
   "A surprising positive view, a general point, a reason, and a funny ending.")),
 card("games", "Are video games a waste of time?",
  ([("x", "Not really, no."),
    ("a", "I think video games can be useful, as long as people don't play too much."),
    ("g", "Most games need you to solve problems, plan ahead and react quickly."),
    ("r", "So they can actually help people develop useful skills."),
    ("c", "Having said that, if someone plays all night and misses school, it's clearly a problem.")],
   "I agree with Beatriz about playing too much.",
   "I'd add that playing online is also how a lot of boys keep in touch with their friends.",
   "A clear no with a condition, general skills, a result, and a limit."),
  ([("x", "Honestly, it depends on the game."),
    ("a", "In my opinion, some games are brilliant and others are designed just to keep you playing."),
    ("g", "In general, games with rewards every few minutes make it very hard to stop."),
    ("e", "For example, I once played a phone game for three hours without noticing — I didn't even enjoy it!"),
    ("c", "Still, a good story game can be as interesting as a film or a book.")],
   "I see what Rodrigo means about phone games.",
   "They're made to be addictive, which I think is unfair on young people.",
   "A distinction between types of game, a general mechanism, an honest example."),
  ([("x", "No, I don't think so."),
    ("a", "I believe games are just another hobby, like reading or watching films."),
    ("g", "People tend to criticise new hobbies — adults once said the same thing about TV."),
    ("r", "The thing is, any hobby is a waste of time if you do it too much."),
    ("c", "Mind you, games should be one hobby among others, not the only one.")],
   "I agree with Leonor about TV.",
   "My grandma says her parents thought rock music was dangerous!",
   "A historical comparison and a principle that applies to every hobby.")),
 card("celebrities", "Why do people like following celebrities?",
  ([("x", "Good question."),
    ("a", "I think people follow celebrities because their lives seem exciting."),
    ("g", "Most people have quite normal lives, so it's fun to see something different."),
    ("r", "It's also something to talk about with friends — who's dating who, what someone was wearing."),
    ("c", "Having said that, celebrities only show a small, perfect part of their lives.")],
   "I agree with Beatriz about the perfect part.",
   "That's why some teenagers feel their own lives are boring.",
   "A reason, a general truth, a social reason, and a warning."),
  ([("x", "Honestly, I think it's about feeling connected."),
    ("a", "In my opinion, social media makes people feel they actually know celebrities."),
    ("g", "In general, when someone posts every day, their followers start to feel like friends."),
    ("e", "For example, my sister gets genuinely upset if her favourite singer doesn't post for a week!"),
    ("c", "Still, it's a strange kind of friendship, because the celebrity doesn't know you exist.")],
   "I see what Rodrigo means about feeling connected.",
   "But some celebrities do reply to fans, and that's why people love them.",
   "A modern reason, a general mechanism, a funny example, and a sharp final point."),
  ([("x", "It depends who the celebrity is."),
    ("a", "I believe people follow celebrities who represent something they want to be."),
    ("g", "People tend to admire people who are successful, brave or talented."),
    ("r", "The thing is, a good role model can inspire young people to work harder."),
    ("e", "For example, Ronaldo came from Madeira, and a lot of kids here train harder because of him.")],
   "I agree with Leonor about role models.",
   "But not every celebrity is a good role model — some are famous for nothing.",
   "A view about role models, a general truth, and a local example.")),
 card("city", "Is it better to grow up in a city or a small town?",
  ([("x", "It's a hard one."),
    ("a", "I think a city gives you more opportunities, but a small town gives you more freedom."),
    ("g", "Most cities have more schools, activities and jobs, which is great for teenagers."),
    ("r", "On the other hand, in small towns children can play outside and walk everywhere safely."),
    ("c", "Mind you, Funchal is quite small for a city, so maybe we get the best of both.")],
   "I agree with Beatriz about Funchal.",
   "It's big enough to have things to do, but you still bump into people you know.",
   "Two sides in one view, then a local twist at the end."),
  ([("x", "A city, for me."),
    ("a", "In my opinion, cities are more exciting and open-minded."),
    ("g", "In general, you meet people from different cultures and backgrounds in a city."),
    ("r", "So you learn to understand people who are different from you."),
    ("c", "Still, cities can be noisy and expensive, and people are often in a hurry.")],
   "I partly agree with Rodrigo.",
   "But in a small town everyone looks after each other, which you don't always find in a city.",
   "A clear preference, a general benefit, a result, and the downside."),
  ([("x", "Honestly, a small town."),
    ("a", "I believe small towns are better for young children, at least."),
    ("g", "People tend to know their neighbours, so children feel safe and looked after."),
    ("e", "For example, my grandparents live in Santana, and everybody there knows everybody."),
    ("c", "Having said that, teenagers often get bored and want to move to the city.")],
   "I agree with Leonor about feeling safe.",
   "Though I'd probably be bored in Santana after one week!",
   "A view about childhood, a general reason, a local example, and an honest concession.")),
])

# ═══════════════════════════ build + checks
def secs(t): return round(len([w for w in t.split() if re.search(r'[A-Za-z0-9]', w)])/2.5)
bad = 0
for ch in CH:
    assert len(ch["cards"]) == 5, ch["id"]
    for c in ch["cards"]:
        assert len(c["alts"]) == 3
        for i, alt in enumerate(c["alts"]):
            for part, lo, hi in (("turn", 20, 30), ("partner", 5, 12)):
                blk = alt[part]
                for s in blk["segs"]:
                    s["marks"] = marks_for(s["t"])[0]
                    if s["m"] not in ("a", "n"): s["wrong"] = wrongs(s["m"])
                blk["frame"] = " ".join(frame_of(s["t"]) for s in blk["segs"])
                ms = [s["m"] for s in blk["segs"]]; tot = sum(secs(s["t"]) for s in blk["segs"])
                ok = lo <= tot <= hi
                if part == "turn": ok = ok and ms[0] in ("x", "a") and "a" in ms and "g" in ms
                if not ok: print(f"!! {ch['id']:7} {c['id']:12} {V[i]['tab']:14} {part:8} {''.join(ms):6} {tot}s"); bad += 1

D = {
 "version": 3, "part": 4,
 "title": "Speaking Part 4 — a view, developed",
 "note": ("Six chapters of five questions. Each card: Candidate A reacts, gives a view and develops it — always widening it "
          "out to people in general — then the examiner turns to Candidate B, who refers to A by name and adds one point. "
          "Three pairs: Beatriz & Tomás, Rodrigo & Inês, Leonor & Diogo. Built by build-part4.py."),
 "tip": "Part 1 asks about you. Part 4 asks about people. Give your view — then widen it out.",
 "modes": {
  "turn":    {"label": "Your view", "limit": 35, "band": [20, 30], "order": ["x", "a", "g", "r", "e", "c"]},
  "partner": {"label": "Joining in", "limit": 15, "band": [5, 12], "order": ["n", "o"]}
 },
 "moves": {
  "x": {"name": "React", "hint": "take a position before you defend it", "ask": "Now put a reaction in front."},
  "a": {"name": "View", "hint": "say what you think, in one sentence", "ask": "Start with your view."},
  "g": {"name": "Generalise", "hint": "about people, not only about you — the Part 4 move", "ask": "Now widen it out to people in general."},
  "r": {"name": "Reason", "hint": "why — or what follows from it", "ask": "Now say why, or what follows."},
  "e": {"name": "Example", "hint": "one real case that proves it", "ask": "Now prove it with one real example."},
  "c": {"name": "Concede", "hint": "the other side, before you finish", "ask": "Now admit the other side."},
  "n": {"name": "Refer", "hint": "your partner, by name", "ask": "Refer to your partner by name."},
  "o": {"name": "Add", "hint": "one point of your own", "ask": "Now add one point of your own."}
 },
 "voices": V,
 "chapters": CH,
 "phraseBank": [
  {"heading": "Reacting", "note": "Take a position before you defend it.",
   "phrases": ["Honestly? Yes…", "Definitely.", "Probably, yes.", "Not really, no.", "It depends on…", "It's not that simple.", "That's a hard one.", "I'm not so sure."]},
  {"heading": "Giving your view", "note": "One clear sentence.",
   "phrases": ["I think…", "I'd say…", "In my opinion,…", "I believe…", "For me,…", "I really don't think…"]},
  {"heading": "Generalising — the Part 4 move", "note": "Part 1 asks about you. Part 4 asks about people.",
   "phrases": ["Generally speaking, people…", "On the whole,…", "In general,…", "Most people…", "A lot of people…", "People tend to…", "These days,…", "Nowadays,…"]},
  {"heading": "Reasons and results", "note": "Why — or what follows from it.",
   "phrases": ["The problem is that…", "The thing is,…", "As a result,…", "That's why…", "…, which means…", "So…"]},
  {"heading": "Examples", "note": "One real case.", "phrases": ["For example,…", "For instance,…", "In my house,…", "At my school,…", "Last year,…", "Where I live,…"]},
  {"heading": "Conceding", "note": "Admit the other side — then you sound fair, not stubborn.",
   "phrases": ["Having said that,…", "Mind you,…", "On the other hand,…", "Still,…", "To be fair,…", "Of course,…"]},
  {"heading": "Joining in (Candidate B)", "note": "Your partner's name first, then one thing of your own.",
   "phrases": ["I agree with Beatriz about…", "I partly agree with Rodrigo. But…", "I see what Leonor means, but…", "I'm not sure I agree with…", "I'd go along with… on that.", "I'd add that…", "For me, though,…"]}
 ]
}
json.dump(D, open(sys.argv[1] if len(sys.argv) > 1 else "part4-views.json", "w"), ensure_ascii=False, indent=1)
print("bad:", bad)
